// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub mod contains;
pub mod endswith;
pub mod startswith;
pub mod strfind;
pub(crate) mod text_utils;
