[package]
name = "rustmat-kernel"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { workspace = true }
zmq = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
rustmat-hir = { workspace = true }
rustmat-ignition = { workspace = true }
rustmat-parser = { workspace = true }
rustmat-builtins = { workspace = true }
rustmat-runtime = { workspace = true }
rustmat-repl = { workspace = true }
rustmat-snapshot = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
tempfile = "3" 