use crate::*;

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "current-folder", title: "Summarize the current folder", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'solver.m'), 'w'); fclose(fid);\nstart = cd(root);\ninfo = what;\ncd(start);\nrmdir(root, 's');", display_output: Some("info.m contains solver.m"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(any(strcmp(info.m, 'solver.m')));" } },
    BuiltinExample { id: "named-folder", title: "Summarize a named folder", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'samples.mat'), 'w'); fclose(fid);\ninfo = what(root);\nrmdir(root, 's');", display_output: Some("info.mat contains samples.mat"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(any(strcmp(info.mat, 'samples.mat')));" } },
    BuiltinExample { id: "source-and-data", title: "Separate source and data files", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'model.m'), 'w'); fclose(fid);\nfid = fopen(fullfile(root, 'model.mat'), 'w'); fclose(fid);\ninfo = what(root);\nrmdir(root, 's');", display_output: Some("source and data names are grouped separately"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(any(strcmp(info.m, 'model.m')));\nassert(any(strcmp(info.mat, 'model.mat')));" } },
    BuiltinExample { id: "classes-and-packages", title: "Find class and package folders", program: "root = tempname();\nmkdir(fullfile(root, '@Vehicle'));\nmkdir(fullfile(root, '+geometry'));\ninfo = what(root);\nrmdir(root, 's');", display_output: Some("classes contains Vehicle and packages contains geometry"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(any(strcmp(info.classes, 'Vehicle')));\nassert(any(strcmp(info.packages, 'geometry')));" } },
    BuiltinExample { id: "ignore-other-files", title: "Ignore unrelated files", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'notes.txt'), 'w'); fclose(fid);\ninfo = what(root);\nrmdir(root, 's');", display_output: Some("recognized file groups are empty"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isempty(info.m));\nassert(isempty(info.mat));\nassert(isempty(info.mex));" } },
];
