export const GATE_PRODUCERS = Object.freeze({
  "catalog-contract": "runmat-builtins-catalog-validator",
  "runtime-binding": "runmat-runtime-binding-validator",
  "documentation-cutover": "builtin-documentation-cutover-audit",
  "native-link": "runmat-native-link-validator",
  "wasm-registry": "runmat-wasm-registry-validator",
  architecture: "runmat-architecture-boundary-validator",
  "focused-tests": "runmat-test-result-adapter",
  "strict-clippy": "runmat-clippy-result-adapter",
  "format-diff": "runmat-format-diff-validator",
  "native-examples": "runmat-builtin-example-verifier",
  "browser-examples": "runmat-builtin-example-verifier",
  "browser-runtime": "runmat-browser-runtime-validator",
  "provider-tests": "runmat-provider-test-adapter",
  "host-tests": "runmat-host-test-adapter",
  "foreign-tests": "runmat-foreign-test-adapter",
  "parallel-tests": "runmat-parallel-test-adapter",
  "deterministic-products": "runmat-generated-product-validator",
  "inventory-delta": "builtin-inventory-delta-validator",
});
