mod contract;
mod documentation;
mod entry;
pub(in crate::catalog::entries::io::repl_fs) mod inference;

use crate::BuiltinCatalogEntry;

pub use contract::{
    SAVEPATH_DESCRIPTOR, SAVEPATH_DIAGNOSTIC_OUTPUTS_EXTENSION,
    SAVEPATH_DIRECTORY_TARGET_EXTENSION, SAVEPATH_ERROR_ARGUMENT_TYPE,
    SAVEPATH_ERROR_CANNOT_RESOLVE, SAVEPATH_ERROR_CANNOT_WRITE, SAVEPATH_ERROR_EMPTY_FILENAME,
    SAVEPATH_ERROR_PROVIDER, SAVEPATH_ERROR_TOO_MANY_INPUTS, SAVEPATH_ERROR_TOO_MANY_OUTPUTS,
    SAVEPATH_NUMERIC_CHARACTER_CODES_EXTENSION,
};

pub use entry::SAVEPATH_CATALOG_ENTRY;

pub(super) const ENTRIES: &[&BuiltinCatalogEntry] = &[&SAVEPATH_CATALOG_ENTRY];
