use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "square-matrix", title: "Square every matrix element", program: "A = [1 2 3; 4 5 6];\nB = arrayfun(@(x) x.^2, A)", display_output: Some("B = [1 4 9; 16 25 36]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(B, [1 4 9; 16 25 36]));" } },
    BuiltinExample { id: "multiple-arrays", title: "Map equal-sized arrays together", program: "A = [1 2 3];\noffset = [10 20 30];\nB = arrayfun(@plus, A, offset)", display_output: Some("B = [11 22 33]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(B, [11 22 33]));" } },
    BuiltinExample { id: "nonuniform-cells", title: "Keep array results in cells", program: "A = [1 2 3];\nB = arrayfun(@(x) [x x], A, \"UniformOutput\", false)", display_output: Some("B is a 1-by-3 cell array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(iscell(B));\nassert(isequal(size(B), [1 3]));\nassert(isequal(B{2}, [2 2]));" } },
    BuiltinExample { id: "exact-uint64", title: "Preserve exact integer callback results", program: "base = uint64(2^53);\nA = [base + uint64(1) base + uint64(3)];\nB = arrayfun(@(x) x + uint64(1), A)", display_output: Some("B retains exact uint64 values above flintmax"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "expected = [base + uint64(2) base + uint64(4)];\nassert(isa(B, \"uint64\"));\nassert(isequal(B, expected));" } },
    BuiltinExample { id: "gpu-sine", title: "Map a supported callback on the GPU", program: "G = gpuArray(single([0 pi/2 pi]));\nS = arrayfun(@sin, G);\nH = gather(S)", display_output: Some("H is single [0 1 0] within floating-point tolerance"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Wgpu, verification: BuiltinExampleVerification::Assertions { source: "assert(isa(H, \"single\"));\nassert(max(abs(double(H) - [0 1 0])) < 1e-5);" } },
];
