use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "string-lengths", title: "Measure text stored in cells", program: "C = {'apple', 'banana', 'cherry'};\nlengths = cellfun(@length, C)", display_output: Some("lengths = [5 6 6]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(lengths, [5 6 6]));" } },
    BuiltinExample { id: "lockstep-cells", title: "Map equal-sized cell arrays together", program: "A = {1, 2, 3};\nB = {4, 5, 6};\ntotals = cellfun(@plus, A, B)", display_output: Some("totals = [5 7 9]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(totals, [5 7 9]));" } },
    BuiltinExample { id: "nonuniform-output", title: "Keep non-scalar results in cells", program: "names = {'Ada', 'Linus', 'Katherine'};\nupper_names = cellfun(@upper, names, 'UniformOutput', false)", display_output: Some("upper_names is a 1-by-3 cell array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(iscell(upper_names));\nassert(isequal(upper_names, {'ADA', 'LINUS', 'KATHERINE'}));" } },
    BuiltinExample { id: "constant-argument", title: "Pass a constant argument to every callback", program: "C = {magic(3), eye(3)};\nrows = cellfun('size', C, 1)", display_output: Some("rows = [3 3]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(rows, [3 3]));" } },
    BuiltinExample { id: "empty-shorthand", title: "Use a supported shorthand function name", program: "C = {[], 1:5, zeros(0, 3)};\nflags = cellfun('isempty', C)", display_output: Some("flags = logical [1 0 1]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(islogical(flags));\nassert(isequal(flags, logical([1 0 1])));" } },
    BuiltinExample { id: "error-handler", title: "Replace callback failures with indexed defaults", program: "C = {1, 2, 3};\nhandler = @(err, value) err.index;\nvalues = cellfun(@(value) value(2), C, 'ErrorHandler', handler)", display_output: Some("values = [1 2 3]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(values, [1 2 3]));" } },
    BuiltinExample { id: "exact-uint64", title: "Collect exact fixed-width integer results", program: "base = uint64(2^53);\nC = {base + uint64(1), base + uint64(3)};\nvalues = cellfun(@(x) x + uint64(1), C)", display_output: Some("values retains exact uint64 storage above flintmax"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isa(values, 'uint64'));\nassert(isequal(values, [base + uint64(2), base + uint64(4)]));" } },
];
