mod acos;
mod asin;
mod atan;
mod cos;
mod cosd;
mod cospi;
mod sin;
mod sind;
mod sinpi;
mod tan;
mod tand;

pub(super) use acos::ACOS_DOCUMENTATION;
pub(super) use asin::ASIN_DOCUMENTATION;
pub(super) use atan::ATAN_DOCUMENTATION;
pub(super) use cos::COS_DOCUMENTATION;
pub(super) use cosd::COSD_DOCUMENTATION;
pub(super) use cospi::COSPI_DOCUMENTATION;
pub(super) use sin::SIN_DOCUMENTATION;
pub(super) use sind::SIND_DOCUMENTATION;
pub(super) use sinpi::SINPI_DOCUMENTATION;
pub(super) use tan::TAN_DOCUMENTATION;
pub(super) use tand::TAND_DOCUMENTATION;
