use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "scalar-order", title: "List scalar structure fields", program: "s = struct('name', 'Ada', 'score', 42);\nfields = fieldnames(s)", display_output: Some("fields = {'name'; 'score'}"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fields, {'name'; 'score'}));" } },
    BuiltinExample { id: "optional-field", title: "Check fields before access", program: "stats = struct('min', 1.2, 'max', 9.8);\nfields = fieldnames(stats);\nhasMedian = any(strcmp(fields, 'median'))", display_output: Some("hasMedian = false"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(~hasMedian);" } },
    BuiltinExample { id: "struct-array-union", title: "List represented structure-array fields", program: "people = struct('name', {'Ada', 'Grace'}, 'id', {101, 102});\nfields = fieldnames(people)", display_output: Some("fields = {'id'; 'name'}"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fields, {'id'; 'name'}));" } },
    BuiltinExample { id: "nested-structure", title: "List fields in a nested structure", program: "config.database = struct('host', 'db.local', 'port', 5432);\nnames = fieldnames(config.database)", display_output: Some("names = {'host'; 'port'}"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(names, {'host'; 'port'}));" } },
    BuiltinExample { id: "empty-structures", title: "Handle empty structures", program: "emptyScalar = struct();\nemptyArray = struct('id', {});\nfs = fieldnames(emptyScalar);\nfa = fieldnames(emptyArray)", display_output: Some("Both results are 0-by-1 cell arrays"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(fs), [0 1]));\nassert(isequal(size(fa), [0 1]));" } },
    BuiltinExample { id: "case-sensitive", title: "Keep case-distinct names", program: "s = struct('name', 1, 'Name', 2);\nnames = fieldnames(s)", display_output: Some("names = {'name'; 'Name'}"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(names, {'name'; 'Name'}));" } },
];
