// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod console;
mod inference;
mod repl_fs;

pub use console::*;
pub(in crate::catalog) use inference::infer;
pub use repl_fs::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(console::ENTRIES.iter().copied());
    repl_fs::extend_entries(values);
}
