// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod matrix_arithmetic;

pub use matrix_arithmetic::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(matrix_arithmetic::ENTRIES.iter().copied());
}
