use crate::*;

const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "existing-file", title: "Test an existing file", program: "root = tempname();\nmkdir(root);\nfile = fullfile(root, 'sample.txt');\nfid = fopen(file, 'w'); fclose(fid);\ntf = isfile(file);\nrmdir(root, 's');", display_output: Some("tf = true"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, verification: BuiltinExampleVerification::Assertions { source: "assert(tf);" } },
    BuiltinExample { id: "folder", title: "Distinguish a folder from a file", program: "root = tempname();\nmkdir(root);\ntf = isfile(root);\nrmdir(root);", display_output: Some("tf = false"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, verification: BuiltinExampleVerification::Assertions { source: "assert(~tf);" } },
    BuiltinExample { id: "string-array", title: "Test a string array", program: "root = tempname();\nmkdir(root);\nfile = fullfile(root, 'present.txt');\nfid = fopen(file, 'w'); fclose(fid);\npaths = [string(file), string(fullfile(root, 'missing.txt'))];\ntf = isfile(paths);\nrmdir(root, 's');", display_output: Some("tf = [true false]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(tf, [true false]));" } },
    BuiltinExample { id: "cell-array", title: "Test a cell array of character rows", program: "root = tempname();\nmkdir(root);\nfile = fullfile(root, 'present.txt');\nfid = fopen(file, 'w'); fclose(fid);\npaths = {file, fullfile(root, 'missing.txt')};\ntf = isfile(paths);\nrmdir(root, 's');", display_output: Some("tf = [true false]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(tf, [true false]));" } },
];

pub(super) const DOCUMENTATION: BuiltinDocumentation = BuiltinDocumentation {
    authority: BuiltinDocumentationAuthority::Catalog, title: Some("isfile"), slug: Some("isfile"), summary: "Test whether paths identify existing files.",
    description: "`isfile(filename)` returns a logical result for each supplied local path. A directory or missing path returns false.",
    keywords: &["isfile", "file", "path", "exists", "predicate"], related: &["isfolder", "exist", "dir", "fullfile"],
    sections: &[BuiltinDocumentationSection { heading: "Inputs and result shape", paragraphs: &["Pass a character row, string array, or cell array of character rows. Character input produces a logical scalar; string and cell inputs produce a logical array with the same dimensions.", "Relative paths use the current folder and a leading `~` expands through the active environment. Filesystem lookup uses RunMat's native or browser filesystem service. Internet and authenticated remote URLs are not currently resolved."] }],
    examples: EXAMPLES, example_exemption: None,
    faqs: &[BuiltinDocumentationFaq { question: "Does isfile return true for a directory?", answer: "No. Use `isfolder` to test directories." }, BuiltinDocumentationFaq { question: "Does a missing path raise an error?", answer: "No. A well-formed path that does not identify a file returns false." }],
    links: &[BuiltinDocumentationLink { label: "isfolder", target: BuiltinDocumentationLinkTarget::Builtin("isfolder") }, BuiltinDocumentationLink { label: "exist", target: BuiltinDocumentationLinkTarget::Builtin("exist") }, BuiltinDocumentationLink { label: "dir", target: BuiltinDocumentationLinkTarget::Builtin("dir") }], media: &[],
    evidence: BuiltinDocumentationEvidence { implementation: &[BuiltinDocumentationLink { label: "File predicate runtime", target: BuiltinDocumentationLinkTarget::Source("https://github.com/runmat-org/runmat/blob/main/crates/runmat-runtime/src/builtins/io/repl_fs/path_predicate/isfile.rs") }], verification: &[BuiltinEvidenceReference { kind: BuiltinEvidenceKind::UnitTest, label: "Scalar and container path predicates", location: "builtins::io::repl_fs::path_predicate::tests" }, BuiltinEvidenceReference { kind: BuiltinEvidenceKind::IntegrationTest, label: "Executable filesystem examples", location: "scripts/runtime/verify-builtin-examples.mjs" }], notes: &[] },
    introduced: Some("R2017b"), status: Some(BuiltinDocumentationStatus::Stable),
};
