[package]
name = "rustmat-plot"
version = "0.0.1"
edition = "2021"

[dependencies]
plotters = { version = "0.3", default-features = false, features = [
    "svg_backend",
    "bitmap_backend",
    "bitmap_encoder",
    "line_series",
    "point_series"
] }
serde = { workspace = true }
serde_yaml = "0.9"
inventory = { workspace = true }

[dev-dependencies]
tempfile = "3"
serial_test = "2"
