// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod operators;
mod relational;
mod tests;

pub use operators::*;
pub use relational::*;
pub use tests::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(
        tests::ENTRY_GROUPS
            .iter()
            .flat_map(|group| group.iter().copied()),
    );
    values.extend(
        operators::ENTRY_GROUPS
            .iter()
            .flat_map(|group| group.iter().copied()),
    );
    values.extend(
        relational::ENTRY_GROUPS
            .iter()
            .flat_map(|group| group.iter().copied()),
    );
}
