// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod accumulation;
mod binning;
mod combinatorics;
mod creation;
mod documentation;
mod grouping;
mod introspection;

pub use accumulation::*;
pub use binning::*;
pub use combinatorics::*;
pub use creation::*;
pub use grouping::*;
pub use introspection::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(accumulation::ENTRIES.iter().copied());
    values.extend(binning::ENTRIES.iter().copied());
    values.extend(combinatorics::ENTRIES.iter().copied());
    creation::extend_entries(values);
    values.extend(grouping::ENTRIES.iter().copied());
    values.extend(
        introspection::ENTRY_GROUPS
            .iter()
            .flat_map(|group| group.iter().copied()),
    );
}

pub(super) fn extend_constants(values: &mut Vec<crate::BuiltinConstantCatalogEntry>) {
    creation::extend_constants(values);
}
