mod aggregate;
mod call;
mod indexing;
mod join;
mod literal;
mod member;
mod mutation;
mod operator;
mod satisfaction;
mod shape;
mod widen;

pub use aggregate::*;
pub use call::infer_call;
pub use indexing::infer_index;
pub use join::FactJoin;
pub use literal::{infer_literal, infer_struct_literal};
pub use member::{infer_member_read, infer_member_write};
pub use mutation::{infer_index_mutation, infer_mutation};
pub use operator::{infer_binary, infer_unary};
pub use satisfaction::*;
pub use shape::*;
pub use widen::FactWiden;
