use crate::*;

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "current-folder", title: "List the current folder", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'current.txt'), 'w'); fclose(fid);\nstart = cd(root);\nlisting = ls;\ncd(start);\nnames = cellstr(listing);\nrmdir(root, 's');", display_output: Some("listing contains current.txt"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(any(strcmp(names, 'current.txt')));" } },
    BuiltinExample { id: "folder", title: "List a folder", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'alpha.txt'), 'w'); fclose(fid);\nmkdir(fullfile(root, 'nested'));\nlisting = ls(root);\nnames = cellstr(listing);\nrmdir(root, 's');", display_output: Some("listing contains alpha.txt and nested"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(any(contains(names, 'alpha.txt')));\nassert(any(contains(names, ['nested' filesep])));" } },
    BuiltinExample { id: "wildcard", title: "List matching files", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'one.m'), 'w'); fclose(fid);\nfid = fopen(fullfile(root, 'two.txt'), 'w'); fclose(fid);\nlisting = ls(fullfile(root, '*.m'));\nnames = cellstr(listing);\nrmdir(root, 's');", display_output: Some("listing contains one.m"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(numel(names) == 1);\nassert(endsWith(names{1}, 'one.m'));" } },
    BuiltinExample { id: "single-file", title: "List one file", program: "root = tempname();\nmkdir(root);\nfile = fullfile(root, 'payload.dat');\nfid = fopen(file, 'w'); fclose(fid);\nlisting = ls(file);\nrmdir(root, 's');", display_output: Some("listing contains payload.dat"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(endsWith(strtrim(listing), 'payload.dat'));" } },
    BuiltinExample { id: "missing", title: "Handle no matches", program: "root = tempname();\nmkdir(root);\nlisting = ls(fullfile(root, '*.missing'));\nrmdir(root);", display_output: Some("listing is empty"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isempty(listing));" } },
    BuiltinExample { id: "portable-rows", title: "Use the portable row layout", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'a.txt'), 'w'); fclose(fid);\nfid = fopen(fullfile(root, 'long-name.txt'), 'w'); fclose(fid);\nlisting = ls(root);\nrmdir(root, 's');", display_output: Some("one padded character row per entry"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(size(listing, 1) == 2);\nassert(size(listing, 2) == length('long-name.txt'));" } },
    BuiltinExample { id: "nested-pattern", title: "Match inside nested folders", program: "root = tempname();\nmkdir(fullfile(root, 'src'));\nfid = fopen(fullfile(root, 'src', 'solver.m'), 'w'); fclose(fid);\nlisting = ls(fullfile(root, 'src', '*.m'));\nrmdir(root, 's');", display_output: Some("listing contains solver.m"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(endsWith(strtrim(listing), 'solver.m'));" } },
];
