// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod random;

pub use random::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(
        random::ENTRY_GROUPS
            .iter()
            .flat_map(|group| group.iter().copied()),
    );
}
