// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod class_registration;
mod conversion;
mod entrypoints;
mod errors;
mod metadata;
mod prelude;
pub mod triangulation;
#[cfg(test)]
mod tests;

use class_registration::*;
use conversion::*;
pub use entrypoints::{
    geometry_inspect_builtin, geometry_list_regions_builtin, geometry_load_builtin,
    geometry_meshes_builtin,
};
#[cfg(target_arch = "wasm32")]
pub(crate) use entrypoints::{
    __runmat_wasm_register_builtin_geometry_inspect_builtin,
    __runmat_wasm_register_builtin_geometry_list_regions_builtin,
    __runmat_wasm_register_builtin_geometry_load_builtin,
    __runmat_wasm_register_builtin_geometry_meshes_builtin,
};
use errors::*;
use metadata::*;
pub use metadata::{
    GEOMETRY_ASSET_CLASS, GEOMETRY_ASSET_JSON_PROPERTY, GEOMETRY_INSPECT_DESCRIPTOR,
    GEOMETRY_LIST_REGIONS_DESCRIPTOR, GEOMETRY_LIST_REGIONS_INTEGER_AUDIT,
    GEOMETRY_LOAD_DESCRIPTOR, GEOMETRY_MESHES_DESCRIPTOR, GEOMETRY_MESHES_INTEGER_AUDIT,
};
use prelude::*;
