use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "center-columns", title: "Subtract each column mean", program: "A = [1 2 10; 3 4 20; 9 6 15];\nC = bsxfun(@minus, A, mean(A))", display_output: Some("C has the same size as A and each column has mean zero"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(C), size(A)));\nassert(max(abs(mean(C))) < 1e-12);" } },
    BuiltinExample { id: "outer-comparison", title: "Compare a column with a row", program: "A = [8; 17; 20; 24];\nB = [0 10 21];\nC = bsxfun(@gt, A, B)", display_output: Some("C is a logical 4-by-3 array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "expected = logical([1 0 0; 1 1 0; 1 1 0; 1 1 1]);\nassert(isa(C, \"logical\"));\nassert(isequal(C, expected));" } },
    BuiltinExample { id: "anonymous-callback", title: "Use an anonymous binary callback", program: "f = @(a,b) a - exp(b);\nC = bsxfun(f, 1:7, pi*[0 1/4 1/3].')", display_output: Some("C contains every pairwise callback result"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "expected = (1:7) - exp(pi*[0 1/4 1/3].');\nassert(max(abs(C(:) - expected(:))) < 1e-12);" } },
    BuiltinExample { id: "exact-integers", title: "Preserve fixed-width integer callback results", program: "base = uint64(2^53);\nA = [base + uint64(1); base + uint64(3)];\nC = bsxfun(@plus, A, uint64([1 2]))", display_output: Some("C is an exact uint64 2-by-2 array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "expected = [base + uint64(2) base + uint64(3); base + uint64(4) base + uint64(5)];\nassert(isa(C, \"uint64\"));\nassert(isequal(C, expected));" } },
    BuiltinExample { id: "empty-logical", title: "Retain the callback class for an empty result", program: "A = zeros(0, 3);\nC = bsxfun(@gt, A, [1 2 3])", display_output: Some("C is an empty logical 0-by-3 array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isa(C, \"logical\"));\nassert(isequal(size(C), [0 3]));\nassert(isempty(C));" } },
];
