use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "scalars", title: "Convert scalar cells", program: "C = {1, 2; 3, 4};\nA = cell2mat(C);", display_output: Some("A is [1 2; 3 4]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(A, [1 2; 3 4]));" } },
    BuiltinExample { id: "blocks", title: "Concatenate rectangular blocks", program: "C = {[1 2], [3 4 5]; [6 7], [8 9 10]};\nA = cell2mat(C);", display_output: Some("A is a 2-by-5 matrix"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(A, [1 2 3 4 5; 6 7 8 9 10]));" } },
    BuiltinExample { id: "logical", title: "Preserve logical storage", program: "C = {true(2,1), false(2,1)};\nA = cell2mat(C);", display_output: Some("A is a 2-by-2 logical array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(islogical(A));\nassert(isequal(A, logical([1 0; 1 0])));" } },
    BuiltinExample { id: "complex", title: "Concatenate complex blocks", program: "C = {1+2i, [3+4i 5+6i]};\nA = cell2mat(C);", display_output: Some("A contains three complex values"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(A, [1+2i 3+4i 5+6i]));" } },
    BuiltinExample { id: "characters", title: "Join character rows", program: "C = {'foo', 'bar'; 'baz', 'qux'};\nA = cell2mat(C);", display_output: Some("A has rows 'foobar' and 'bazqux'"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(A, ['foobar'; 'bazqux']));" } },
    BuiltinExample { id: "pages", title: "Tile N-dimensional blocks", program: "C = {ones(2,2,3), 2*ones(2,1,3)};\nA = cell2mat(C);", display_output: Some("A has shape 2-by-3-by-3"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(A), [2 3 3]));" } },
    BuiltinExample { id: "empty", title: "Convert an empty cell grid", program: "C = {[], []; [], []};\nA = cell2mat(C);", display_output: Some("A is a 0-by-0 double array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(A), [0 0]));\nassert(isa(A, 'double'));" } },
    BuiltinExample { id: "exact-integer", title: "Preserve wide integer values", program: "C = {0x0020000000000001u64, 0xFFFFFFFFFFFFFFFFu64};\nA = cell2mat(C);", display_output: Some("A is an exact 1-by-2 uint64 array"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isa(A, 'uint64'));\nassert(A(1) == 0x0020000000000001u64);\nassert(A(2) == 0xFFFFFFFFFFFFFFFFu64);" } },
];
