// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod bitwise;
mod discrete;
pub mod elementwise;
mod integer_division;
mod linalg;
mod reduction;
mod rounding;
mod trigonometry;

pub use bitwise::*;
pub use discrete::*;
pub use elementwise::*;
pub use integer_division::*;
pub use linalg::*;
pub use reduction::*;
pub use rounding::*;
pub use trigonometry::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    elementwise::extend_entries(values);
    bitwise::extend_entries(values);
    values.extend(discrete::ENTRIES.iter().copied());
    values.extend(integer_division::ENTRIES.iter().copied());
    linalg::extend_entries(values);
    reduction::extend_entries(values);
    values.extend(rounding::ENTRIES.iter().copied());
    trigonometry::extend_entries(values);
}
