// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

#[path = "core/common.rs"]
pub(crate) mod common;
#[path = "core/context.rs"]
pub mod context;
#[path = "core/engine.rs"]
pub(crate) mod engine;
#[path = "core/error.rs"]
mod error;
#[path = "core/figure_scene.rs"]
mod figure_scene;
#[cfg(feature = "plot-core")]
#[path = "core/geometry_scene.rs"]
mod geometry_scene;
#[path = "core/gpu_helpers.rs"]
pub(crate) mod gpu_helpers;
#[path = "core/import_registry.rs"]
mod import_registry;
#[path = "core/perf.rs"]
pub(crate) mod perf;
#[path = "core/point.rs"]
pub(crate) mod point;
#[path = "core/properties.rs"]
pub(crate) mod properties;
#[path = "core/runtime_mode.rs"]
mod runtime_mode;
#[path = "core/state.rs"]
pub(crate) mod state;
#[path = "core/style.rs"]
pub(crate) mod style;
#[path = "core/test_support.rs"]
mod test_support;
#[path = "core/web.rs"]
pub mod web;
pub(crate) mod type_resolvers;
#[path = "ops/addpoints.rs"]
pub(crate) mod addpoints;
#[path = "ops/ancestor.rs"]
pub(crate) mod ancestor;
#[path = "ops/animatedline.rs"]
pub(crate) mod animatedline;
#[path = "ops/area.rs"]
pub(crate) mod area;
#[path = "ops/axes.rs"]
pub(crate) mod axes;
#[path = "ops/axis_scale.rs"]
pub(crate) mod axis_scale;
#[path = "ops/axis_tick_angle.rs"]
pub(crate) mod axis_tick_angle;
#[path = "ops/axis_tick_format.rs"]
pub(crate) mod axis_tick_format;
#[path = "ops/axis_tick_labels.rs"]
pub(crate) mod axis_tick_labels;
#[path = "ops/axis_ticks.rs"]
pub(crate) mod axis_ticks;
#[path = "ops/bar.rs"]
pub(crate) mod bar;
#[path = "ops/caxis.rs"]
pub(crate) mod caxis;
#[path = "ops/clf.rs"]
pub(crate) mod clf;
#[path = "ops/clim.rs"]
pub(crate) mod clim;
#[path = "ops/close.rs"]
pub(crate) mod close;
#[path = "ops/cmds.rs"]
pub(crate) mod cmds;
#[path = "ops/colormap_arrays.rs"]
pub(crate) mod colormap_arrays;
#[path = "ops/colororder.rs"]
pub(crate) mod colororder;
#[path = "ops/contour.rs"]
pub(crate) mod contour;
#[path = "ops/contour3.rs"]
pub(crate) mod contour3;
#[path = "ops/contourf.rs"]
pub(crate) mod contourf;
#[path = "ops/copyobj.rs"]
pub(crate) mod copyobj;
#[path = "ops/daspect.rs"]
pub(crate) mod daspect;
#[path = "ops/data_tip_text_row.rs"]
pub(crate) mod data_tip_text_row;
#[path = "ops/datacursormode.rs"]
pub(crate) mod datacursormode;
#[path = "ops/drawnow.rs"]
pub(crate) mod drawnow;
#[path = "ops/errorbar.rs"]
pub(crate) mod errorbar;
#[path = "ops/fcontour.rs"]
pub(crate) mod fcontour;
#[path = "ops/figure.rs"]
pub(crate) mod figure;
#[path = "ops/figure_persistence.rs"]
pub(crate) mod figure_persistence;
#[path = "ops/fill.rs"]
pub(crate) mod fill;
#[path = "ops/fill3.rs"]
pub(crate) mod fill3;
#[path = "ops/findobj.rs"]
pub(crate) mod findobj;
#[path = "ops/fsurf.rs"]
pub(crate) mod fsurf;
#[path = "ops/gca.rs"]
pub(crate) mod gca;
#[path = "ops/gcf.rs"]
pub(crate) mod gcf;
#[path = "ops/get.rs"]
pub(crate) mod get;
#[path = "ops/gobjects.rs"]
pub(crate) mod gobjects;
#[path = "ops/groot.rs"]
pub(crate) mod groot;
#[path = "ops/heatmap.rs"]
pub(crate) mod heatmap;
#[path = "ops/hist.rs"]
pub mod hist;
#[path = "ops/histogram.rs"]
pub(crate) mod histogram;
#[path = "ops/histogram2.rs"]
pub(crate) mod histogram2;
#[path = "ops/hold.rs"]
pub(crate) mod hold;
#[path = "ops/image.rs"]
pub(crate) mod image;
#[path = "ops/imagesc.rs"]
pub(crate) mod imagesc;
#[path = "ops/imshow.rs"]
pub(crate) mod imshow;
#[path = "ops/isgraphics.rs"]
pub(crate) mod isgraphics;
#[path = "ops/ishandle.rs"]
pub(crate) mod ishandle;
#[path = "ops/legend.rs"]
pub(crate) mod legend;
#[path = "ops/line.rs"]
pub(crate) mod line;
#[path = "ops/linkaxes.rs"]
pub(crate) mod linkaxes;
#[path = "ops/loglog.rs"]
pub(crate) mod loglog;
#[path = "ops/mesh.rs"]
pub(crate) mod mesh;
#[path = "ops/meshc.rs"]
pub(crate) mod meshc;
#[path = "ops/common/mod.rs"]
pub(crate) mod op_common;
#[path = "ops/opengl.rs"]
pub(crate) mod opengl;
#[path = "ops/pan.rs"]
pub(crate) mod pan;
#[path = "ops/patch.rs"]
pub(crate) mod patch;
#[path = "ops/pie.rs"]
pub(crate) mod pie;
#[path = "ops/plot.rs"]
pub(crate) mod plot;
#[path = "ops/plot3.rs"]
pub(crate) mod plot3;
#[path = "ops/plotmatrix.rs"]
pub(crate) mod plotmatrix;
#[path = "ops/plotyy.rs"]
pub(crate) mod plotyy;
#[path = "ops/polarhistogram.rs"]
pub(crate) mod polarhistogram;
#[path = "ops/polarplot.rs"]
pub(crate) mod polarplot;
#[path = "ops/polarscatter.rs"]
pub(crate) mod polarscatter;
#[path = "ops/print.rs"]
pub(crate) mod print;
#[path = "ops/quiver.rs"]
pub(crate) mod quiver;
#[path = "ops/quiver3.rs"]
pub(crate) mod quiver3;
#[path = "ops/ribbon.rs"]
pub(crate) mod ribbon;
#[path = "ops/scatter.rs"]
pub(crate) mod scatter;
#[path = "ops/scatter3.rs"]
pub(crate) mod scatter3;
#[path = "ops/scatterplot.rs"]
pub(crate) mod scatterplot;
#[path = "ops/semilogx.rs"]
pub(crate) mod semilogx;
#[path = "ops/semilogy.rs"]
pub(crate) mod semilogy;
#[path = "ops/set.rs"]
pub(crate) mod set;
#[path = "ops/sgtitle.rs"]
pub(crate) mod sgtitle;
#[path = "ops/sphere.rs"]
pub(crate) mod sphere;
#[path = "ops/stackedplot.rs"]
pub(crate) mod stackedplot;
#[path = "ops/stairs.rs"]
pub(crate) mod stairs;
#[path = "ops/stem.rs"]
pub(crate) mod stem;
#[path = "ops/subplot.rs"]
pub(crate) mod subplot;
#[path = "ops/subtitle.rs"]
pub(crate) mod subtitle;
#[path = "ops/suptitle.rs"]
pub(crate) mod suptitle;
#[path = "ops/surf.rs"]
pub(crate) mod surf;
#[path = "ops/surfc.rs"]
pub(crate) mod surfc;
#[path = "ops/text.rs"]
pub(crate) mod text;
#[path = "ops/textscatter.rs"]
pub(crate) mod textscatter;
#[path = "ops/title.rs"]
pub(crate) mod title;
#[path = "ops/triplot.rs"]
pub(crate) mod triplot;
#[path = "ops/view.rs"]
pub(crate) mod view;
#[path = "ops/waitbar.rs"]
pub(crate) mod waitbar;
#[path = "ops/wordcloud.rs"]
pub(crate) mod wordcloud;
#[path = "ops/xlabel.rs"]
pub(crate) mod xlabel;
#[path = "ops/xlim.rs"]
pub(crate) mod xlim;
#[path = "ops/xline.rs"]
pub(crate) mod xline;
#[path = "ops/xscale.rs"]
pub(crate) mod xscale;
#[path = "ops/xtickangle.rs"]
pub(crate) mod xtickangle;
#[path = "ops/xtickformat.rs"]
pub(crate) mod xtickformat;
#[path = "ops/xticklabels.rs"]
pub(crate) mod xticklabels;
#[path = "ops/xticks.rs"]
pub(crate) mod xticks;
#[path = "ops/ylabel.rs"]
pub(crate) mod ylabel;
#[path = "ops/ylim.rs"]
pub(crate) mod ylim;
#[path = "ops/yline.rs"]
pub(crate) mod yline;
#[path = "ops/yscale.rs"]
pub(crate) mod yscale;
#[path = "ops/ytickangle.rs"]
pub(crate) mod ytickangle;
#[path = "ops/ytickformat.rs"]
pub(crate) mod ytickformat;
#[path = "ops/yticklabels.rs"]
pub(crate) mod yticklabels;
#[path = "ops/yticks.rs"]
pub(crate) mod yticks;
#[path = "ops/zlabel.rs"]
pub(crate) mod zlabel;
#[path = "ops/zlim.rs"]
pub(crate) mod zlim;
#[path = "ops/zoom.rs"]
pub(crate) mod zoom;
pub mod ops;
#[cfg(test)]
pub(crate) mod tests;

#[cfg(feature = "plot-core")]
pub use engine::{
    render_figure_png_bytes, render_figure_png_bytes_with_axes_cameras,
    render_figure_png_bytes_with_camera, render_figure_rgba_bytes,
    render_figure_rgba_bytes_with_axes_cameras, render_figure_rgba_bytes_with_camera,
    render_figure_snapshot, render_figure_snapshot_with_camera_state,
    render_geometry_scene_snapshot,
};
pub(crate) use error::{plotting_error, plotting_error_with_source};
pub use figure_scene::present_figure_on_surface;
#[cfg(feature = "plot-core")]
pub use figure_scene::{
    export_figure_scene, export_figure_scene_with_policy, import_figure_scene,
    import_figure_scene_async, import_figure_scene_from_path_async, import_runtime_figure,
};
#[cfg(feature = "plot-core")]
pub use geometry_scene::{
    append_geometry_scene_chunks, clone_geometry_scene, close_geometry_scene,
    export_geometry_scene, import_geometry_scene, import_geometry_scene_payload,
    present_geometry_scene_on_surface,
};
#[cfg(feature = "plot-core")]
pub use import_registry::register_imported_geometry_scene;
pub use perf::{
    set_scatter_target_points, set_scene_export_budget_bytes, set_surface_vertex_budget,
};
pub use properties::resolve_plot_handle;
pub use runtime_mode::{set_runtime_plotting_mode, RuntimePlottingMode};
pub use state::{
    clear_figure, clone_figure, close_figure, configure_subplot, current_axes_state,
    current_figure_handle, figure_handles, import_figure, install_figure_observer, link_axes,
    new_figure_handle, record_recent_figure, reset_hold_state_for_run, reset_plot_state,
    reset_recent_figures, select_axes_for_figure, select_figure, set_hold, take_recent_figures,
    FigureAxesState, FigureError, FigureEventKind, FigureEventView, FigureHandle, HoldMode,
    LinkAxesMode,
};
#[doc(hidden)]
pub use test_support::{lock_plot_test_context, PlotTestLockGuard};
pub use web::{
    bind_surface_to_figure, clear_closed_figure_surfaces, detach_surface, fit_surface_extents,
    get_surface_camera_state, install_surface, invalidate_surface_revisions,
    pick_geometry_scene_region, present_surface, render_current_scene, reset_surface_camera,
    resize_surface, set_geometry_scene_presentation, set_plot_theme_config,
    set_surface_camera_state, web_renderer_ready, PlotCameraProjection, PlotCameraState,
    PlotSurfaceCameraState,
};
#[cfg(all(target_arch = "wasm32", feature = "plot-web"))]
pub use web::{handle_plot_surface_event, take_surface_host_actions, PlotSurfaceHostAction};
