pub(in crate::catalog) mod fieldnames;
pub(in crate::catalog) mod getfield;
pub(in crate::catalog) mod isfield;
pub(in crate::catalog) mod orderfields;
pub(in crate::catalog) mod rmfield;
pub(in crate::catalog) mod setfield;
pub(in crate::catalog) mod structfun;

pub use fieldnames::{
    FIELDNAMES_CATALOG_ENTRY, FIELDNAMES_DESCRIPTOR, FIELDNAMES_ERROR_INTERNAL,
    FIELDNAMES_ERROR_INVALID_TARGET, FIELDNAMES_EXTENSIONS, FIELDNAMES_INTEGER_AUDIT,
    FIELDNAMES_OBJECT_FAMILY_EXTENSION,
};
pub use getfield::{
    GETFIELD_CATALOG_ENTRY, GETFIELD_DESCRIPTOR, GETFIELD_ERRORS, GETFIELD_ERROR_FIELD_EXPECTED,
    GETFIELD_ERROR_FIELD_NAME_TYPE, GETFIELD_ERROR_INDEX_INVALID,
    GETFIELD_ERROR_INDEX_OUT_OF_BOUNDS, GETFIELD_ERROR_INDEX_SELECTOR_TYPE,
    GETFIELD_ERROR_INDEX_SHAPE, GETFIELD_ERROR_INTERNAL, GETFIELD_ERROR_INVALID_HANDLE,
    GETFIELD_ERROR_MISSING_FIELD, GETFIELD_ERROR_NON_STRUCT_REFERENCE,
    GETFIELD_ERROR_NOT_ENOUGH_INPUTS, GETFIELD_ERROR_OBJECT_PROPERTY,
    GETFIELD_ERROR_PROPERTY_PRIVATE_ACCESS, GETFIELD_EXTENSIONS,
    GETFIELD_INDEXED_RESIDENT_EXTENSION, GETFIELD_INTEGER_CAPABILITIES,
    GETFIELD_OBJECT_FAMILY_EXTENSION, GETFIELD_TEXTUAL_INDEX_EXTENSION,
};
pub use isfield::{
    ISFIELD_CATALOG_ENTRY, ISFIELD_DESCRIPTOR, ISFIELD_ERROR_CELL_ELEMENT_TYPE,
    ISFIELD_ERROR_FIELD_NAME_TYPE, ISFIELD_ERROR_INTERNAL, ISFIELD_INTEGER_AUDIT,
};
pub use orderfields::{
    ORDERFIELDS_CATALOG_ENTRY, ORDERFIELDS_DESCRIPTOR, ORDERFIELDS_ERROR_DUPLICATE_FIELD,
    ORDERFIELDS_ERROR_DUPLICATE_INDEX, ORDERFIELDS_ERROR_EMPTY_FIELD_NAME,
    ORDERFIELDS_ERROR_EMPTY_STRUCT_ARRAY, ORDERFIELDS_ERROR_FIELD_MISMATCH,
    ORDERFIELDS_ERROR_INDEX_NOT_INTEGER, ORDERFIELDS_ERROR_INDEX_OUT_OF_RANGE,
    ORDERFIELDS_ERROR_INVALID_NAME_LIST, ORDERFIELDS_ERROR_INVALID_ORDER,
    ORDERFIELDS_ERROR_INVALID_PERMUTATION, ORDERFIELDS_ERROR_INVALID_REFERENCE,
    ORDERFIELDS_ERROR_INVALID_TARGET, ORDERFIELDS_ERROR_NO_FIELDS,
    ORDERFIELDS_ERROR_REBUILD_FAILED, ORDERFIELDS_ERROR_TOO_MANY_INPUTS,
    ORDERFIELDS_ERROR_UNKNOWN_FIELD, ORDERFIELDS_INTEGER_CAPABILITIES,
};
pub use rmfield::{
    RMFIELD_CATALOG_ENTRY, RMFIELD_DESCRIPTOR, RMFIELD_ERROR_FIELD_NAME_EMPTY,
    RMFIELD_ERROR_FIELD_NAME_TYPE, RMFIELD_ERROR_INVALID_TARGET, RMFIELD_ERROR_MISSING_FIELD,
    RMFIELD_ERROR_NOT_ENOUGH_INPUTS, RMFIELD_ERROR_REBUILD_FAILED, RMFIELD_EXTENSIONS,
    RMFIELD_INTEGER_CAPABILITIES, RMFIELD_VARIADIC_EXTENSION,
};
pub use setfield::{
    SETFIELD_CATALOG_ENTRY, SETFIELD_DESCRIPTOR, SETFIELD_ERRORS, SETFIELD_ERROR_FIELD_EXPECTED,
    SETFIELD_ERROR_FIELD_NAME_TYPE, SETFIELD_ERROR_INDEX_INVALID,
    SETFIELD_ERROR_INDEX_OUT_OF_BOUNDS, SETFIELD_ERROR_INDEX_SELECTOR_TYPE,
    SETFIELD_ERROR_INDEX_SHAPE, SETFIELD_ERROR_INTERNAL, SETFIELD_ERROR_INVALID_HANDLE,
    SETFIELD_ERROR_MISSING_FIELD, SETFIELD_ERROR_NON_STRUCT_ASSIGNMENT,
    SETFIELD_ERROR_NOT_ENOUGH_INPUTS, SETFIELD_ERROR_OBJECT_PROPERTY,
    SETFIELD_ERROR_PROPERTY_PRIVATE_ACCESS, SETFIELD_ERROR_PROPERTY_STATIC_ACCESS,
    SETFIELD_EXTENSIONS, SETFIELD_INDEXED_RESIDENT_EXTENSION, SETFIELD_INTEGER_CAPABILITIES,
    SETFIELD_OBJECT_FAMILY_EXTENSION, SETFIELD_TEXTUAL_INDEX_EXTENSION,
};
pub use structfun::{
    STRUCTFUN_CATALOG_ENTRY, STRUCTFUN_DESCRIPTOR, STRUCTFUN_ERROR_FUNCTION_ERROR,
    STRUCTFUN_ERROR_INTERNAL, STRUCTFUN_ERROR_INVALID_INPUT, STRUCTFUN_ERROR_NOT_SCALAR_STRUCT,
    STRUCTFUN_ERROR_UNDEFINED_FUNCTION, STRUCTFUN_ERROR_UNIFORM_OUTPUT,
    STRUCTFUN_INTEGER_CAPABILITIES,
};

pub(super) fn extend_entries(entries: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    super::super::extend_groups(
        entries,
        &[
            fieldnames::ENTRIES,
            getfield::ENTRIES,
            isfield::ENTRIES,
            orderfields::ENTRIES,
            rmfield::ENTRIES,
            setfield::ENTRIES,
            structfun::ENTRIES,
        ],
    );
}
