use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "ascii-order", title: "Sort field names", program: "s = struct('b', 1, 'B', 2, 'a', 3, 'A', 4);\nt = orderfields(s)", display_output: Some("t has fields A, B, a, b"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fieldnames(t), {'A'; 'B'; 'a'; 'b'}));\nassert(t.A == 4 && t.b == 1);" } },
    BuiltinExample { id: "reference", title: "Match another structure", program: "source = struct('y', 20, 'x', 10);\ntemplate = struct('x', 0, 'y', 0);\naligned = orderfields(source, template)", display_output: Some("aligned follows template field order"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fieldnames(aligned), {'x'; 'y'}));\nassert(aligned.x == 10 && aligned.y == 20);" } },
    BuiltinExample { id: "name-list", title: "Supply field names", program: "s = struct('a', 1, 'b', 2, 'c', 3);\nt = orderfields(s, {'c', 'a', 'b'})", display_output: Some("t follows the requested names"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fieldnames(t), {'c'; 'a'; 'b'}));" } },
    BuiltinExample { id: "permutation", title: "Supply original positions", program: "s = struct('first', 1, 'second', 2, 'third', 3);\nt = orderfields(s, [3 1 2])", display_output: Some("third becomes the first field"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fieldnames(t), {'third'; 'first'; 'second'}));" } },
    BuiltinExample { id: "permutation-output", title: "Reuse the returned permutation", program: "s = struct('z', 1, 'x', 2, 'y', 3);\n[t, p] = orderfields(s);\nu = orderfields(s, p)", display_output: Some("p is [2; 3; 1] and u matches t"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(p, [2; 3; 1]));\nassert(isequal(fieldnames(u), fieldnames(t)));" } },
    BuiltinExample { id: "typed-payload", title: "Preserve typed field values", program: "s = struct('wide', uint64(18446744073709551615), 'small', int8(-7));\nt = orderfields(s)", display_output: Some("the reordered values retain uint64 and int8 storage"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(strcmp(class(t.wide), 'uint64'));\nassert(strcmp(class(t.small), 'int8'));" } },
];
