mod acos;
mod acosh;
mod angle_conversion;
mod asin;
mod asinh;
mod atan;
mod atan2;
mod atanh;
mod cos;
mod cosd;
mod cosh;
mod cospi;
mod sin;
mod sind;
mod sinh;
mod sinpi;
mod tan;
mod tand;
mod tanh;

pub use acos::*;
pub use acosh::*;
pub use angle_conversion::*;
pub use asin::*;
pub use asinh::*;
pub use atan::*;
pub use atan2::*;
pub use atanh::*;
pub use cos::*;
pub use cosd::*;
pub use cosh::*;
pub use cospi::*;
pub use sin::*;
pub use sind::*;
pub use sinh::*;
pub use sinpi::*;
pub use tan::*;
pub use tand::*;
pub use tanh::*;

pub(super) fn extend_entries(out: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    out.extend_from_slice(acos::ENTRIES);
    out.extend_from_slice(acosh::ENTRIES);
    out.extend_from_slice(asin::ENTRIES);
    out.extend_from_slice(asinh::ENTRIES);
    out.extend_from_slice(atan::ENTRIES);
    out.extend_from_slice(atan2::ENTRIES);
    out.extend_from_slice(atanh::ENTRIES);
    out.extend_from_slice(angle_conversion::ENTRIES);
    out.extend_from_slice(cos::ENTRIES);
    out.extend_from_slice(cosh::ENTRIES);
    out.extend_from_slice(cosd::ENTRIES);
    out.extend_from_slice(cospi::ENTRIES);
    out.extend_from_slice(sin::ENTRIES);
    out.extend_from_slice(sinpi::ENTRIES);
    out.extend_from_slice(sinh::ENTRIES);
    out.extend_from_slice(sind::ENTRIES);
    out.extend_from_slice(tan::ENTRIES);
    out.extend_from_slice(tand::ENTRIES);
    out.extend_from_slice(tanh::ENTRIES);
}
