// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod acos;
mod acosh;
mod angle_conversion;
mod asin;
mod asinh;
mod atan;
mod atan2;
mod atanh;
mod cos;
mod cosd;
mod cosh;
mod cospi;
mod sin;
mod sind;
mod sinh;
mod sinpi;
mod tan;
mod tand;
mod tanh;

pub use acos::*;
pub use acosh::*;
pub use angle_conversion::*;
pub use asin::*;
pub use asinh::*;
pub use atan::*;
pub use atan2::*;
pub use atanh::*;
pub use cos::*;
pub use cosd::*;
pub use cosh::*;
pub use cospi::*;
pub use sin::*;
pub use sind::*;
pub use sinh::*;
pub use sinpi::*;
pub use tan::*;
pub use tand::*;
pub use tanh::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(acos::ENTRIES.iter().copied());
    values.extend(acosh::ENTRIES.iter().copied());
    values.extend(asin::ENTRIES.iter().copied());
    values.extend(asinh::ENTRIES.iter().copied());
    values.extend(atan::ENTRIES.iter().copied());
    values.extend(atan2::ENTRIES.iter().copied());
    values.extend(atanh::ENTRIES.iter().copied());
    values.extend(angle_conversion::ENTRIES.iter().copied());
    values.extend(cos::ENTRIES.iter().copied());
    values.extend(cosh::ENTRIES.iter().copied());
    values.extend(cosd::ENTRIES.iter().copied());
    values.extend(cospi::ENTRIES.iter().copied());
    values.extend(sin::ENTRIES.iter().copied());
    values.extend(sinpi::ENTRIES.iter().copied());
    values.extend(sinh::ENTRIES.iter().copied());
    values.extend(sind::ENTRIES.iter().copied());
    values.extend(tan::ENTRIES.iter().copied());
    values.extend(tand::ENTRIES.iter().copied());
    values.extend(tanh::ENTRIES.iter().copied());
}
