mod context;
mod current_execution;
mod futures;
mod pools;

pub(super) use context::{
    LABINDEX_DOCUMENTATION, NUMLABS_DOCUMENTATION, SPMD_INDEX_DOCUMENTATION,
    SPMD_SIZE_DOCUMENTATION,
};
pub(super) use current_execution::{
    GET_CURRENT_JOB_DOCUMENTATION, GET_CURRENT_TASK_DOCUMENTATION, GET_CURRENT_WORKER_DOCUMENTATION,
};
pub(super) use futures::{
    FETCH_NEXT_DOCUMENTATION, FETCH_OUTPUTS_DOCUMENTATION, PARFEVAL_DOCUMENTATION,
    PARFEVAL_ON_ALL_DOCUMENTATION,
};
pub(super) use pools::{GCP_DOCUMENTATION, PARPOOL_DOCUMENTATION};
