// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub(crate) mod binary_arithmetic;
pub(crate) mod bsxfun;
pub(crate) mod complex_components;
pub(crate) mod complex_construction;
mod domain_probe;
pub(crate) mod error_functions;
mod exact_integer;
pub(crate) mod exponentials;
pub(crate) mod extended_precision;
pub(crate) mod floating_conversions;
pub(crate) mod gamma_functions;
pub(crate) mod heaviside;
pub(crate) mod hypot;
pub(crate) mod integer_arithmetic;
pub(crate) mod integer_conversions;
pub(crate) mod logarithms;
pub(crate) mod magnitude_phase_sign;
pub(crate) mod numeric_limits;
pub(crate) mod powers_of_two;
pub(crate) mod rescale;
pub(crate) mod roots;
pub(crate) mod sparse;
pub(crate) mod sparse_integer;
pub(crate) mod typecast;
mod unary_provider;
