use std::collections::BTreeMap;

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct BoundaryNodeCompletionDiagnostic {
    pub reason: &'static str,
    pub missing_face_count: usize,
    pub cap_candidate_count: usize,
    pub outside_candidate_count: usize,
    pub duplicate_candidate_count: usize,
    pub max_rejected_scaled_jacobian: f64,
    pub rejected_scaled_jacobian_bins: BTreeMap<String, usize>,
    pub max_rejected_cap_height_ratio: f64,
    pub rejected_cap_height_ratio_bins: BTreeMap<String, usize>,
    pub rejected_scaled_jacobian_worst_corner_bins: BTreeMap<&'static str, usize>,
    pub rejected_cap_node_ids: BTreeMap<u32, usize>,
    pub split_cap_candidate_count: usize,
    pub split_cap_pass_count: usize,
    pub max_split_cap_scaled_jacobian: f64,
    pub split_cap_scaled_jacobian_bins: BTreeMap<String, usize>,
    pub split_cap_scaled_jacobian_worst_corner_bins: BTreeMap<&'static str, usize>,
    pub split_cap_apex_limited_node_ids: BTreeMap<u32, usize>,
    pub edge_split_cap_candidate_count: usize,
    pub edge_split_cap_pass_count: usize,
    pub max_edge_split_cap_scaled_jacobian: f64,
    pub edge_split_cap_scaled_jacobian_bins: BTreeMap<String, usize>,
    pub edge_split_cap_scaled_jacobian_worst_corner_bins: BTreeMap<&'static str, usize>,
    pub edge_split_cap_apex_limited_node_ids: BTreeMap<u32, usize>,
    pub three_edge_split_cap_candidate_count: usize,
    pub three_edge_split_cap_pass_count: usize,
    pub max_three_edge_split_cap_scaled_jacobian: f64,
    pub three_edge_split_cap_scaled_jacobian_bins: BTreeMap<String, usize>,
    pub three_edge_split_cap_scaled_jacobian_worst_corner_bins: BTreeMap<&'static str, usize>,
    pub three_edge_split_cap_apex_limited_node_ids: BTreeMap<u32, usize>,
    pub rejected_by_reason: BTreeMap<&'static str, usize>,
}
