use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "quadrants", title: "Split a matrix into four blocks", program: "A = reshape(1:16, 4, 4);\nC = mat2cell(A, [2 2], [1 3]);", display_output: Some("C is a 2-by-2 cell array"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(C), [2 2]));\nassert(isequal(C{2,2}, [7 11 15; 8 12 16]));" } },
    BuiltinExample { id: "column", title: "Partition a column vector", program: "v = (1:6)';\nC = mat2cell(v, [2 1 3]);", display_output: Some("The final block contains [4; 5; 6]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(C), [3 1]));\nassert(isequal(C{3}, [4; 5; 6]));" } },
    BuiltinExample { id: "pages", title: "Partition a 3-D array", program: "A = reshape(1:24, [3 4 2]);\nC = mat2cell(A, [1 2], [2 2], [1 1]);\nblock = C{2,1,2};", display_output: Some("C has shape 2-by-2-by-2"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(C), [2 2 2]));\nassert(isequal(block, reshape([14 15 17 18], [2 2 1])));" } },
    BuiltinExample { id: "empty-block", title: "Keep zero-sized blocks", program: "A = zeros(3, 2);\nC = mat2cell(A, [0 3], [1 1]);", display_output: Some("The first cell-grid row contains empty 0-by-1 blocks"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(C{1,1}), [0 1]));\nassert(isequal(size(C{2,2}), [3 1]));" } },
    BuiltinExample { id: "characters", title: "Partition character rows", program: "names = ['foo '; 'bar '; 'baz '];\nC = mat2cell(names, [1 2], size(names, 2));", display_output: Some("C contains one row and one two-row character block"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(C{1,1}, 'foo '));\nassert(isequal(C{2,1}, ['bar '; 'baz ']));" } },
    BuiltinExample { id: "logical", title: "Preserve logical blocks", program: "A = logical([1 0 1; 0 1 0]);\nC = mat2cell(A, 2, [1 1 1]);", display_output: Some("Each cell contains a logical column"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(islogical(C{1,2}));\nassert(isequal(C{1,2}, logical([0; 1])));" } },
    BuiltinExample { id: "exact-partitions", title: "Use exact integer partition vectors", program: "A = uint64([1 2 3 4]);\nC = mat2cell(A, uint8(1), uint16([2 2]));", display_output: Some("RunMat partitions exact uint64 data with typed integer controls"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isa(C{1,1}, 'uint64'));\nassert(isequal(C{1,2}, uint64([3 4])));" } },
];
