[package]
name = "rustmat-macros"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
inventory = "0.1"
rustmat-builtins = { path = "../rustmat-builtins" }

[dev-dependencies]
trybuild = "1"
