[package]
name = "rustmat-runtime"
version = "0.0.1"
edition = "2021"

[dependencies]
inventory = { workspace = true }
rustmat-builtins = { workspace = true }
rustmat-macros = { workspace = true }

[dev-dependencies]
rustmat-macros = { workspace = true } 