[package]
name = "rustmat-runtime"
version = "0.0.1"
edition = "2021"

[dependencies]
inventory = { workspace = true }
rustmat-builtins = { workspace = true }
rustmat-macros = { workspace = true }

# BLAS/LAPACK bindings for high-performance linear algebra (optional)
blas = { version = "0.22", optional = true }
lapack = { version = "0.19", optional = true }

# Platform-specific BLAS/LAPACK implementations
[target.'cfg(target_os = "macos")'.dependencies]
# Use Apple's Accelerate framework on macOS (works on both Intel and Apple Silicon)
accelerate-src = { version = "0.3", optional = true }

[target.'cfg(not(target_os = "macos"))'.dependencies]
# Use OpenBLAS on other platforms
openblas-src = { version = "0.10", features = ["cblas", "lapacke"], optional = true }

[features]
default = []
# High-performance BLAS/LAPACK support using platform-native libraries
# macOS: Uses Apple's Accelerate framework (WORKS on both Intel and Apple Silicon!)
# Other platforms: Uses OpenBLAS
# Usage: cargo test --features blas-lapack
blas-lapack = ["blas", "lapack", "accelerate-src", "openblas-src"]

[dev-dependencies]
rustmat-macros = { workspace = true } 