// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub(crate) mod codistributor;
pub(crate) mod current;
pub(crate) mod future;
pub(crate) mod pool;
pub(crate) mod primitives;
pub(crate) mod spmd_context;
