// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub mod bitwise;
pub mod discrete;
pub mod elementwise;
pub mod fft;
pub mod integer_division;
pub mod interpolation;
pub mod linalg;
pub mod ode;
pub mod optim;
pub mod poly;
pub mod reduction;
pub(crate) mod resident_real_unary;
pub mod rounding;
pub mod signal;
pub mod symbolic;
pub mod trigonometry;
pub mod type_resolvers;
