use crate::*;

const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "existing-folder", title: "Test an existing folder", program: "root = tempname();\nmkdir(root);\ntf = isfolder(root);\nrmdir(root);", display_output: Some("tf = true"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(tf);" } },
    BuiltinExample { id: "file", title: "Distinguish a file from a folder", program: "root = tempname();\nmkdir(root);\nfile = fullfile(root, 'sample.txt');\nfid = fopen(file, 'w'); fclose(fid);\ntf = isfolder(file);\nrmdir(root, 's');", display_output: Some("tf = false"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(~tf);" } },
    BuiltinExample { id: "string-array", title: "Test a string array", program: "root = tempname();\nmkdir(root);\nfolders = [string(root), string(fullfile(root, 'missing'))];\ntf = isfolder(folders);\nrmdir(root);", display_output: Some("tf = [true false]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(tf, [true false]));" } },
    BuiltinExample { id: "cell-array", title: "Test a cell array of character rows", program: "root = tempname();\nmkdir(root);\nfolders = {root, fullfile(root, 'missing')};\ntf = isfolder(folders);\nrmdir(root);", display_output: Some("tf = [true false]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(tf, [true false]));" } },
];

pub(super) const DOCUMENTATION: BuiltinDocumentation = BuiltinDocumentation {
    authority: BuiltinDocumentationAuthority::Catalog, title: Some("isfolder"), slug: Some("isfolder"), summary: "Test whether paths identify existing folders.",
    description: "`isfolder(folderName)` returns a logical result for each supplied local path. A file or missing path returns false.",
    keywords: &["isfolder", "folder", "directory", "path", "exists", "predicate"], related: &["isfile", "exist", "dir", "mkdir"],
    sections: &[BuiltinDocumentationSection { heading: "Inputs and result shape", paragraphs: &["Pass a character row, string array, or cell array of character rows. Character input produces a logical scalar; string and cell inputs produce a logical array with the same dimensions.", "Relative paths use the current folder and a leading `~` expands through the active environment. Filesystem lookup uses RunMat's native or browser filesystem service. Remote URLs are not currently resolved."] }],
    examples: EXAMPLES, example_exemption: None,
    faqs: &[BuiltinDocumentationFaq { question: "Does isfolder return true for a file?", answer: "No. Use `isfile` to test files." }, BuiltinDocumentationFaq { question: "Does a missing path raise an error?", answer: "No. A well-formed path that does not identify a folder returns false." }],
    links: &[BuiltinDocumentationLink { label: "isfile", target: BuiltinDocumentationLinkTarget::Builtin("isfile") }, BuiltinDocumentationLink { label: "exist", target: BuiltinDocumentationLinkTarget::Builtin("exist") }, BuiltinDocumentationLink { label: "dir", target: BuiltinDocumentationLinkTarget::Builtin("dir") }], media: &[],
    evidence: BuiltinDocumentationEvidence { implementation: &[BuiltinDocumentationLink { label: "Folder predicate runtime", target: BuiltinDocumentationLinkTarget::Source("https://github.com/runmat-org/runmat/blob/main/crates/runmat-runtime/src/builtins/io/repl_fs/path_predicate/isfolder.rs") }], verification: &[BuiltinEvidenceReference { kind: BuiltinEvidenceKind::UnitTest, label: "Scalar and container path predicates", location: "builtins::io::repl_fs::path_predicate::tests" }, BuiltinEvidenceReference { kind: BuiltinEvidenceKind::IntegrationTest, label: "Executable filesystem examples", location: "scripts/runtime/verify-builtin-examples.mjs" }], notes: &[] },
    introduced: Some("R2017b"), status: Some(BuiltinDocumentationStatus::Stable),
};
