import json
import unittest
from pathlib import Path


class ExternalReferenceBaselineTests(unittest.TestCase):
    def test_coupled_and_em_threshold_metrics_present(self):
        baseline_path = Path("scripts/analysis/reference_data/m6_external_reference_baseline.json")
        payload = json.loads(baseline_path.read_text())
        metrics = payload.get("metrics")
        self.assertIsInstance(metrics, list)

        required = {
            ("nonlinear_assembly_gpu_provider", "nonlinear_total_increments"),
            ("nonlinear_assembly_gpu_provider", "nonlinear_failed_increments"),
            ("nonlinear_assembly_gpu_provider", "nonlinear_iteration_spike_count"),
            (
                "nonlinear_assembly_stress_gpu_provider",
                "nonlinear_stress_total_increments",
            ),
            ("nonlinear_assembly_stress_gpu_provider", "nonlinear_stress_stall_count"),
            (
                "nonlinear_assembly_stress_gpu_provider",
                "nonlinear_stress_iteration_spike_count",
            ),
            (
                "nonlinear_softening_proxy_gpu_provider",
                "nonlinear_softening_total_increments",
            ),
            (
                "nonlinear_softening_proxy_gpu_provider",
                "nonlinear_softening_spike_count",
            ),
            (
                "nonlinear_softening_proxy_gpu_provider",
                "nonlinear_softening_backtrack_bursts",
            ),
            ("nonlinear_load_path_mix_gpu_provider", "nonlinear_path_mix_total_increments"),
            (
                "nonlinear_load_path_mix_gpu_provider",
                "nonlinear_path_mix_max_backtracks_per_increment",
            ),
            (
                "nonlinear_load_path_mix_gpu_provider",
                "nonlinear_path_mix_backtrack_bursts",
            ),
            (
                "nonlinear_load_path_mix_gpu_provider",
                "nonlinear_path_mix_effective_modulus_scale",
            ),
            (
                "nonlinear_load_path_mix_gpu_provider",
                "nonlinear_path_mix_material_spread_ratio",
            ),
            ("nonlinear_load_path_mix_gpu_provider", "thermo_nonlinear_severity"),
            (
                "nonlinear_load_path_mix_gpu_provider",
                "electro_nonlinear_joule_heating_scale",
            ),
            (
                "nonlinear_load_path_mix_gpu_provider",
                "electro_nonlinear_conductivity_spread_ratio",
            ),
            ("nonlinear_load_path_mix_gpu_provider", "electro_nonlinear_severity_peak"),
            (
                "nonlinear_plasticity_proxy_gpu_provider",
                "plasticity_nonlinear_severity_peak",
            ),
            (
                "nonlinear_plasticity_proxy_gpu_provider",
                "plasticity_nonlinear_severity_mean",
            ),
            ("nonlinear_contact_proxy_gpu_provider", "contact_nonlinear_severity_peak"),
            ("nonlinear_contact_proxy_gpu_provider", "contact_nonlinear_severity_mean"),
            (
                "nonlinear_contact_frictionless_reference_gpu_provider",
                "contact_frictionless_severity_peak",
            ),
            (
                "nonlinear_contact_frictionless_reference_gpu_provider",
                "contact_frictionless_severity_mean",
            ),
            (
                "nonlinear_plastic_hardening_reference_gpu_provider",
                "plasticity_hardening_reference_severity_peak",
            ),
            (
                "nonlinear_plastic_hardening_reference_gpu_provider",
                "plasticity_hardening_reference_severity_mean",
            ),
            (
                "thermo_gradient_benign_gpu_provider",
                "thermo_gradient_benign_spread_ratio",
            ),
            (
                "thermo_gradient_benign_gpu_provider",
                "thermo_gradient_benign_heterogeneity",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_sigma_omega_scale_mean",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_sigma_omega_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_sigma_omega_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permittivity_frequency_scale_mean",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permittivity_frequency_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permittivity_frequency_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permeability_frequency_scale_mean",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permeability_frequency_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permeability_frequency_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_phase_attenuation_mean",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_phase_attenuation_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_coupling_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_phase_conductivity_attenuation_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_loss_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_applied_current_a",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_solver_conditioning_proxy",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_reference_frequency_hz",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_sweep_count",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_resonance_peak_frequency_hz",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_resonance_peak_flux_density",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_resonance_bandwidth_hz",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_resonance_q_proxy",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "electromagnetic_resonance_flux_gain",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_sigma_omega_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_sigma_omega_scale_mean",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_sigma_omega_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permittivity_frequency_scale_mean",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permittivity_frequency_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permittivity_frequency_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permeability_frequency_scale_mean",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permeability_frequency_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permeability_frequency_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_region_contrast_index",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_phase_attenuation_mean",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_phase_attenuation_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_coupling_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_phase_conductivity_attenuation_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_loss_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_applied_current_a",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_solver_conditioning_proxy",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_reference_frequency_hz",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_sweep_count",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_resonance_peak_frequency_hz",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_resonance_peak_flux_density",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_resonance_bandwidth_hz",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_resonance_q_proxy",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "electromagnetic_resonance_flux_gain",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_anchor_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_real_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_interference_index",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_interference_index",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "em_boundary_kernel_boundary_localization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "em_boundary_kernel_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "em_boundary_kernel_insulation_leakage_proxy",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_placeholder_quality",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_real_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_source_region_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_source_localization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_source_interference_index",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_boundary_condition_localization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_relative_permittivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_relative_permeability_spread_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_region_coefficient_contrast_index",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "electromagnetic_insulation_leakage_proxy",
            ),
            ("cfd_steady_gpu_provider", "cfd_reference_density_kg_per_m3"),
            ("cfd_steady_gpu_provider", "cfd_dynamic_viscosity_pa_s"),
            ("cfd_steady_gpu_provider", "cfd_inlet_velocity_m_per_s"),
            ("cfd_steady_gpu_provider", "cfd_turbulence_intensity"),
            ("cfd_steady_gpu_provider", "cfd_reynolds_proxy"),
            ("cfd_steady_gpu_provider", "cfd_profile_point_count"),
            ("cfd_steady_gpu_provider", "transient_max_residual_norm"),
            ("cfd_steady_gpu_provider", "transient_max_energy_growth_ratio"),
            ("cfd_steady_gpu_provider", "transient_prepared_cache_hit_ratio"),
            ("cfd_steady_gpu_provider", "transient_prepared_cache_misses"),
            ("cht_coupled_gpu_provider", "cht_reference_density_kg_per_m3"),
            ("cht_coupled_gpu_provider", "cht_dynamic_viscosity_pa_s"),
            ("cht_coupled_gpu_provider", "cht_inlet_velocity_m_per_s"),
            ("cht_coupled_gpu_provider", "cht_turbulence_intensity"),
            ("cht_coupled_gpu_provider", "cht_applied_temperature_delta_k"),
            ("cht_coupled_gpu_provider", "cht_reynolds_proxy"),
            ("cht_coupled_gpu_provider", "cht_profile_point_count"),
            ("cht_coupled_gpu_provider", "cht_step_count"),
            ("cht_coupled_gpu_provider", "cht_time_step_s"),
            ("cht_coupled_gpu_provider", "transient_max_residual_norm"),
            ("cht_coupled_gpu_provider", "transient_max_energy_growth_ratio"),
            ("cht_coupled_gpu_provider", "transient_prepared_cache_hit_ratio"),
            ("cht_coupled_gpu_provider", "transient_prepared_cache_misses"),
            ("fsi_coupled_gpu_provider", "fsi_reference_density_kg_per_m3"),
            ("fsi_coupled_gpu_provider", "fsi_dynamic_viscosity_pa_s"),
            ("fsi_coupled_gpu_provider", "fsi_inlet_velocity_m_per_s"),
            ("fsi_coupled_gpu_provider", "fsi_turbulence_intensity"),
            ("fsi_coupled_gpu_provider", "fsi_reynolds_proxy"),
            ("fsi_coupled_gpu_provider", "fsi_profile_point_count"),
            ("fsi_coupled_gpu_provider", "fsi_step_count"),
            ("fsi_coupled_gpu_provider", "fsi_time_step_s"),
            ("fsi_coupled_gpu_provider", "fsi_structural_step_count"),
            ("fsi_coupled_gpu_provider", "fsi_cfd_profile_point_count"),
            ("fsi_coupled_gpu_provider", "transient_max_residual_norm"),
            ("fsi_coupled_gpu_provider", "transient_max_energy_growth_ratio"),
            ("fsi_coupled_gpu_provider", "transient_prepared_cache_hit_ratio"),
            ("fsi_coupled_gpu_provider", "transient_prepared_cache_misses"),
            (
                "thermo_mech_kickoff_gpu_provider",
                "thermo_mech_thermal_strain_scale",
            ),
            (
                "thermo_mech_kickoff_gpu_provider",
                "thermo_mech_thermal_load_scale",
            ),
            (
                "thermo_mech_kickoff_gpu_provider",
                "thermo_mech_effective_modulus_scale",
            ),
            (
                "thermo_mech_kickoff_gpu_provider",
                "thermo_mech_material_spread_ratio",
            ),
            (
                "thermo_mech_kickoff_gpu_provider",
                "thermo_mech_assignment_heterogeneity_index",
            ),
            (
                "thermo_mech_kickoff_gpu_provider",
                "thermo_mech_transient_severity",
            ),
            (
                "thermo_mech_kickoff_gpu_provider",
                "thermo_mech_transient_time_scale_mean",
            ),
            (
                "thermo_ramp_smooth_gpu_provider",
                "thermo_ramp_smooth_temporal_variation",
            ),
            (
                "thermo_ramp_smooth_gpu_provider",
                "thermo_ramp_smooth_spatial_gradient_index",
            ),
            (
                "thermo_ramp_smooth_gpu_provider",
                "thermo_ramp_smooth_spatial_coverage_ratio",
            ),
            (
                "thermo_ramp_smooth_gpu_provider",
                "thermo_ramp_smooth_field_extrapolation_ratio",
            ),
            (
                "thermo_ramp_smooth_gpu_provider",
                "thermo_ramp_smooth_field_clamp_ratio",
            ),
            (
                "thermo_ramp_smooth_field_artifact_gpu_provider",
                "thermo_ramp_smooth_temporal_variation",
            ),
            (
                "thermo_ramp_smooth_field_artifact_gpu_provider",
                "thermo_ramp_smooth_spatial_gradient_index",
            ),
            (
                "thermo_ramp_smooth_field_artifact_gpu_provider",
                "thermo_ramp_smooth_spatial_coverage_ratio",
            ),
            (
                "thermo_ramp_smooth_field_artifact_gpu_provider",
                "thermo_ramp_smooth_field_extrapolation_ratio",
            ),
            (
                "thermo_ramp_smooth_field_artifact_gpu_provider",
                "thermo_ramp_smooth_field_clamp_ratio",
            ),
            (
                "thermo_gradient_pathological_gpu_provider",
                "thermo_gradient_pathological_spread_ratio",
            ),
            (
                "thermo_gradient_pathological_gpu_provider",
                "thermo_gradient_pathological_heterogeneity",
            ),
            (
                "thermo_gradient_pathological_gpu_provider",
                "thermo_gradient_pathological_temporal_variation",
            ),
            (
                "thermo_shock_oscillatory_gpu_provider",
                "thermo_shock_oscillatory_temporal_variation",
            ),
            (
                "thermo_shock_oscillatory_gpu_provider",
                "thermo_shock_oscillatory_spatial_gradient_index",
            ),
            (
                "thermo_shock_oscillatory_gpu_provider",
                "thermo_shock_oscillatory_spatial_coverage_ratio",
            ),
            (
                "thermo_shock_oscillatory_gpu_provider",
                "thermo_shock_oscillatory_field_extrapolation_ratio",
            ),
            (
                "thermo_shock_oscillatory_gpu_provider",
                "thermo_shock_oscillatory_field_clamp_ratio",
            ),
            (
                "thermo_shock_oscillatory_field_artifact_gpu_provider",
                "thermo_shock_oscillatory_temporal_variation",
            ),
            (
                "thermo_shock_oscillatory_field_artifact_gpu_provider",
                "thermo_shock_oscillatory_spatial_gradient_index",
            ),
            (
                "thermo_shock_oscillatory_field_artifact_gpu_provider",
                "thermo_shock_oscillatory_spatial_coverage_ratio",
            ),
            (
                "thermo_shock_oscillatory_field_artifact_gpu_provider",
                "thermo_shock_oscillatory_field_extrapolation_ratio",
            ),
            (
                "thermo_shock_oscillatory_field_artifact_gpu_provider",
                "thermo_shock_oscillatory_field_clamp_ratio",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_max_residual_norm",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_min_temperature_k",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_max_temperature_k",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_conductivity_spread_ratio",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_heat_capacity_spread_ratio",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_spatial_gradient_index",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_monotonic_response_fraction",
            ),
            (
                "thermal_standalone_ramp_gpu_provider",
                "thermal_standalone_response_realization_ratio",
            ),
            (
                "electro_thermal_joule_benign_gpu_provider",
                "electro_thermal_benign_joule_heating_scale",
            ),
            (
                "electro_thermal_joule_benign_gpu_provider",
                "electro_thermal_benign_conductivity_spread_ratio",
            ),
            (
                "electro_thermal_joule_benign_gpu_provider",
                "electro_thermal_benign_transient_severity_peak",
            ),
            (
                "electro_thermal_joule_benign_gpu_provider",
                "electro_thermal_benign_temporal_variation",
            ),
            (
                "electro_thermal_joule_benign_gpu_provider",
                "electro_thermal_benign_time_scale_mean",
            ),
            (
                "electro_thermal_joule_pathological_gpu_provider",
                "electro_thermal_pathological_joule_heating_scale",
            ),
            (
                "electro_thermal_joule_pathological_gpu_provider",
                "electro_thermal_pathological_conductivity_spread_ratio",
            ),
            (
                "electro_thermal_joule_pathological_gpu_provider",
                "electro_thermal_pathological_transient_severity_peak",
            ),
            (
                "electro_thermal_joule_pathological_gpu_provider",
                "electro_thermal_pathological_temporal_variation",
            ),
            (
                "electro_thermal_joule_pathological_gpu_provider",
                "electro_thermal_pathological_time_scale_mean",
            ),
            (
                "nonlinear_plastic_hardening_reference_complex_gpu_provider",
                "plasticity_hardening_reference_complex_severity_peak",
            ),
            (
                "nonlinear_plastic_hardening_reference_complex_gpu_provider",
                "plasticity_hardening_reference_complex_severity_mean",
            ),
            (
                "nonlinear_plastic_hardening_reference_complex_gpu_provider",
                "plasticity_hardening_reference_complex_load_realization_ratio",
            ),
            (
                "nonlinear_contact_frictionless_reference_complex_gpu_provider",
                "contact_frictionless_complex_severity_peak",
            ),
            (
                "nonlinear_contact_frictionless_reference_complex_gpu_provider",
                "contact_frictionless_complex_severity_mean",
            ),
            (
                "nonlinear_contact_frictionless_reference_complex_gpu_provider",
                "contact_frictionless_complex_load_amplification_ratio",
            ),
            (
                "acoustic_harmonic_gpu_provider",
                "acoustic_max_m_orthogonality_offdiag",
            ),
            (
                "acoustic_harmonic_gpu_provider",
                "acoustic_min_relative_frequency_separation",
            ),
            ("acoustic_harmonic_gpu_provider", "acoustic_mode_count"),
            ("acoustic_harmonic_gpu_provider", "acoustic_residual_warn_threshold"),
        }
        observed = set()
        for metric in metrics:
            fixture_id = metric.get("fixture_id")
            if not isinstance(fixture_id, str):
                continue
            source = metric.get("source", "field")
            if source == "threshold_assertion":
                metric_name = metric.get("assertion_name")
            else:
                metric_name = metric.get("name")
            if isinstance(metric_name, str):
                observed.add((fixture_id, metric_name))
        missing = required - observed
        self.assertFalse(
            missing,
            f"missing coupled/em external reference metrics: {sorted(missing)}",
        )


if __name__ == "__main__":
    unittest.main()
