import json
import unittest
from pathlib import Path


class ExternalReferenceBaselineTests(unittest.TestCase):
    def test_coupled_and_em_threshold_metrics_present(self):
        baseline_path = Path("scripts/analysis/reference_data/m6_external_reference_baseline.json")
        payload = json.loads(baseline_path.read_text())
        metrics = payload.get("metrics")
        self.assertIsInstance(metrics, list)

        required = {
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_sigma_omega_scale_mean",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_sigma_omega_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_sigma_omega_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_phase_attenuation_mean",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_coupling_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_dispersive_phase_conductivity_attenuation_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_boundary_energy_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_homogeneous_gpu_provider",
                "em_homogeneous_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_sigma_omega_scale_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_sigma_omega_scale_mean",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_sigma_omega_response_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_material_heterogeneity_index",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_conductivity_spread_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_region_contrast_index",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_phase_attenuation_mean",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_coupling_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_dispersive_phase_conductivity_attenuation_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_flux_divergence_proxy",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_heterogeneous_gpu_provider",
                "em_heterogeneous_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_anchor_ratio",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_real_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_imag_residual_norm",
            ),
            (
                "electromagnetic_reference_boundary_penalty_stress_gpu_provider",
                "em_boundary_penalty_conditioning_contribution",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_energy_consistency_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_multi_region_phased_source_gpu_provider",
                "em_phased_source_interference_index",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_sparse_assignments_gpu_provider",
                "em_sparse_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_fallback_coefficient_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_assignment_coverage_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_source_realization_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_boundary_anchor_ratio",
            ),
            (
                "electromagnetic_reference_fallback_heavy_gpu_provider",
                "em_fallback_heavy_energy_imbalance_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_interference_index",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_overlap_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_region_coverage_ratio",
            ),
            (
                "electromagnetic_reference_overlap_interference_gpu_provider",
                "em_overlap_source_material_alignment_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "em_boundary_kernel_boundary_localization_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "em_boundary_kernel_ground_anchor_effectiveness_ratio",
            ),
            (
                "electromagnetic_reference_boundary_kernel_gpu_provider",
                "em_boundary_kernel_insulation_leakage_proxy",
            ),
            ("cfd_steady_gpu_provider", "cfd_reference_density_kg_per_m3"),
            ("cfd_steady_gpu_provider", "cfd_reynolds_proxy"),
            ("cht_coupled_gpu_provider", "cht_applied_temperature_delta_k"),
            ("cht_coupled_gpu_provider", "cht_reynolds_proxy"),
            ("fsi_coupled_gpu_provider", "fsi_reynolds_proxy"),
            ("fsi_coupled_gpu_provider", "fsi_structural_step_count"),
            (
                "thermo_gradient_pathological_gpu_provider",
                "thermo_gradient_pathological_spread_ratio",
            ),
            (
                "thermo_gradient_pathological_gpu_provider",
                "thermo_gradient_pathological_temporal_variation",
            ),
            (
                "thermo_shock_oscillatory_gpu_provider",
                "thermo_shock_oscillatory_temporal_variation",
            ),
            (
                "electro_thermal_joule_pathological_gpu_provider",
                "electro_thermal_pathological_conductivity_spread_ratio",
            ),
            (
                "electro_thermal_joule_pathological_gpu_provider",
                "electro_thermal_pathological_temporal_variation",
            ),
            (
                "nonlinear_plastic_hardening_reference_complex_gpu_provider",
                "plasticity_hardening_reference_complex_load_realization_ratio",
            ),
            (
                "nonlinear_contact_frictionless_reference_complex_gpu_provider",
                "contact_frictionless_complex_load_amplification_ratio",
            ),
            (
                "acoustic_harmonic_gpu_provider",
                "acoustic_max_m_orthogonality_offdiag",
            ),
            (
                "acoustic_harmonic_gpu_provider",
                "acoustic_min_relative_frequency_separation",
            ),
            ("acoustic_harmonic_gpu_provider", "acoustic_mode_count"),
            ("acoustic_harmonic_gpu_provider", "acoustic_residual_warn_threshold"),
        }
        observed = {
            (metric.get("fixture_id"), metric.get("assertion_name"))
            for metric in metrics
            if metric.get("source") == "threshold_assertion"
        }
        missing = required - observed
        self.assertFalse(
            missing,
            f"missing coupled/em external reference metrics: {sorted(missing)}",
        )


if __name__ == "__main__":
    unittest.main()
