// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod author_study;
mod boundary;
mod comparison;
mod contracts;
mod document;
mod domain_interface;
mod entrypoints;
mod errors;
mod geometry;
mod integer_serialization;
mod load_step;
mod material;
mod model;
mod options_json;
mod output;
mod plot;
mod registry;
mod results;
mod run_options;
mod study;
mod value_decode;
#[cfg(test)]
mod tests;

pub use contracts::{
    FEA_AUTHOR_STUDY_DESCRIPTOR, FEA_BOUNDARY_CONDITION_DESCRIPTOR,
    FEA_BOUNDARY_CONDITION_INTEGER_CAPABILITIES, FEA_COMPARE_DESCRIPTOR, FEA_COMPONENT_DESCRIPTOR,
    FEA_DOMAIN_DESCRIPTOR, FEA_DOMAIN_INTEGER_CAPABILITIES, FEA_FIELD_DESCRIPTOR,
    FEA_INTERFACE_DESCRIPTOR, FEA_INTERFACE_INTEGER_CAPABILITIES, FEA_LOAD_CASE_DESCRIPTOR,
    FEA_LOAD_CASE_INTEGER_CAPABILITIES, FEA_LOAD_DESCRIPTOR, FEA_MATERIAL_ASSIGNMENT_DESCRIPTOR,
    FEA_MATERIAL_DESCRIPTOR, FEA_MATERIAL_INTEGER_CAPABILITIES, FEA_MODEL_DESCRIPTOR,
    FEA_PLAN_DESCRIPTOR, FEA_PLOT_DESCRIPTOR, FEA_RESULTS_DESCRIPTOR,
    FEA_RESULTS_INTEGER_CAPABILITIES, FEA_RUN_DESCRIPTOR, FEA_RUN_OPTIONS_DESCRIPTOR,
    FEA_RUN_OPTIONS_INTEGER_CAPABILITIES, FEA_STEP_DESCRIPTOR, FEA_STRUCTURAL_INTEGER_AUDIT,
    FEA_STUDY_DESCRIPTOR, FEA_SWEEP_DESCRIPTOR, FEA_TRENDS_DESCRIPTOR,
    FEA_TRENDS_INTEGER_CAPABILITIES, FEA_VALIDATE_DESCRIPTOR,
};
pub use entrypoints::{
    fea_author_study_builtin, fea_boundary_condition_builtin, fea_compare_builtin,
    fea_domain_builtin, fea_field_builtin, fea_interface_builtin, fea_load_builtin,
    fea_load_case_builtin, fea_material_assignment_builtin, fea_material_builtin,
    fea_model_builtin, fea_plan_builtin, fea_plot_builtin, fea_results_builtin, fea_run_builtin,
    fea_run_options_builtin, fea_step_builtin, fea_study_builtin, fea_sweep_builtin,
    fea_trends_builtin, fea_validate_builtin,
};
#[cfg(target_arch = "wasm32")]
pub(crate) use entrypoints::{
    __runmat_wasm_register_builtin_fea_author_study_builtin,
    __runmat_wasm_register_builtin_fea_boundary_condition_builtin,
    __runmat_wasm_register_builtin_fea_compare_builtin,
    __runmat_wasm_register_builtin_fea_domain_builtin,
    __runmat_wasm_register_builtin_fea_field_builtin,
    __runmat_wasm_register_builtin_fea_interface_builtin,
    __runmat_wasm_register_builtin_fea_load_builtin,
    __runmat_wasm_register_builtin_fea_load_case_builtin,
    __runmat_wasm_register_builtin_fea_material_assignment_builtin,
    __runmat_wasm_register_builtin_fea_material_builtin,
    __runmat_wasm_register_builtin_fea_model_builtin,
    __runmat_wasm_register_builtin_fea_plan_builtin,
    __runmat_wasm_register_builtin_fea_plot_builtin,
    __runmat_wasm_register_builtin_fea_results_builtin,
    __runmat_wasm_register_builtin_fea_run_builtin,
    __runmat_wasm_register_builtin_fea_run_options_builtin,
    __runmat_wasm_register_builtin_fea_step_builtin,
    __runmat_wasm_register_builtin_fea_study_builtin,
    __runmat_wasm_register_builtin_fea_sweep_builtin,
    __runmat_wasm_register_builtin_fea_trends_builtin,
    __runmat_wasm_register_builtin_fea_validate_builtin,
};
