#[macro_use]
mod contract;
mod double;
mod single;

pub use double::{
    CATALOG_ENTRY as DOUBLE_CATALOG_ENTRY, DESCRIPTOR as DOUBLE_DESCRIPTOR,
    ERROR_GPU_UNSUPPORTED as DOUBLE_ERROR_GPU_UNSUPPORTED, ERROR_INTERNAL as DOUBLE_ERROR_INTERNAL,
    ERROR_INVALID_ARGUMENT as DOUBLE_ERROR_INVALID_ARGUMENT,
    ERROR_INVALID_INPUT as DOUBLE_ERROR_INVALID_INPUT, EXTENSIONS as DOUBLE_EXTENSIONS,
    INTEGER_CAPABILITIES as DOUBLE_INTEGER_CAPABILITIES, LIKE_EXTENSION as DOUBLE_LIKE_EXTENSION,
};
pub use single::{
    CATALOG_ENTRY as SINGLE_CATALOG_ENTRY, DESCRIPTOR as SINGLE_DESCRIPTOR,
    ERROR_GPU_UNSUPPORTED as SINGLE_ERROR_GPU_UNSUPPORTED, ERROR_INTERNAL as SINGLE_ERROR_INTERNAL,
    ERROR_INVALID_ARGUMENT as SINGLE_ERROR_INVALID_ARGUMENT,
    ERROR_INVALID_INPUT as SINGLE_ERROR_INVALID_INPUT, EXTENSIONS as SINGLE_EXTENSIONS,
    INTEGER_CAPABILITIES as SINGLE_INTEGER_CAPABILITIES,
    LIKE_EXTENSION as SINGLE_LIKE_OUTPUT_EXTENSION,
};

pub(super) const ENTRIES: &[&crate::BuiltinCatalogEntry] =
    &[&DOUBLE_CATALOG_ENTRY, &SINGLE_CATALOG_ENTRY];

#[cfg(test)]
mod tests;
