use super::*;

mod assertions;

use assertions::*;

#[test]
fn evidence_summarizes_mesh_without_raw_sizing_samples() {
    let mesh = AnalysisMeshArtifact {
        schema_version: ANALYSIS_MESH_SCHEMA_VERSION.to_string(),
        mesh_id: "mesh_1".to_string(),
        nodes: vec![
            node(1, [0.0, 0.0, 0.0]),
            node(2, [1.0, 0.0, 0.0]),
            node(3, [0.0, 1.0, 0.0]),
            node(4, [0.0, 0.0, 1.0]),
        ],
        volume_elements: vec![AnalysisVolumeElement {
            element_id: "tetrahedron_1".to_string(),
            kind: VolumeElementKind::Tetrahedron4,
            node_ids: vec![1, 2, 3, 4],
            material_region_id: "solid".to_string(),
            provenance: Vec::new(),
        }],
        boundary_faces: vec![AnalysisBoundaryFace {
            face_id: "face_1".to_string(),
            kind: BoundaryElementKind::Tri3,
            node_ids: vec![1, 2, 3],
            adjacent_volume_element_ids: vec!["tetrahedron_1".to_string()],
            region_ids: vec!["fixed".to_string()],
            provenance: vec![MeshEntityProvenance {
                source_geometry_id: "geo".to_string(),
                source_geometry_revision: 1,
                source_entity_kind: SourceEntityKind::Face,
                source_entity_id: "source_face_1".to_string(),
                region_ids: vec!["fixed".to_string()],
            }],
        }],
        boundary_edges: vec![
            boundary_edge("edge_1", [1, 2]),
            boundary_edge("edge_2", [2, 3]),
            boundary_edge("edge_3", [1, 3]),
        ],
        quality: AnalysisMeshQualityReport {
            min_scaled_jacobian: 0.5,
            min_exact_scaled_jacobian: 0.45,
            mean_aspect_ratio: 2.0,
            max_aspect_ratio: 2.0,
            inverted_element_count: 0,
            mean_boundary_projection_error_m: 0.0,
            max_boundary_projection_error_m: 0.0,
            elements: vec![ElementQuality {
                element_id: "tetrahedron_1".to_string(),
                scaled_jacobian: 0.5,
                exact_scaled_jacobian: 0.45,
                aspect_ratio: 2.0,
                volume_m3: 1.0 / 6.0,
            }],
        },
        sizing: MeshSizingField {
            growth_rate: Some(1.4),
            samples: vec![
                SizingSample {
                    position_m: [0.0, 0.0, 0.0],
                    target_size_m: 0.25,
                    reason: Some("load_region".to_string()),
                },
                SizingSample {
                    position_m: [0.5, 0.0, 0.0],
                    target_size_m: 0.2,
                    reason: Some("cad.curvature".to_string()),
                },
                SizingSample {
                    position_m: [0.0, 0.5, 0.0],
                    target_size_m: 0.15,
                    reason: Some("cad.interface".to_string()),
                },
            ],
            anisotropic_samples: vec![
                AnisotropicSizingSample {
                    position_m: [0.2, 0.2, 0.2],
                    target_sizes_m: [0.02, 0.04, 0.08],
                    directions: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
                    reason: Some("boundary_layer".to_string()),
                },
                AnisotropicSizingSample {
                    position_m: [0.3, 0.2, 0.2],
                    target_sizes_m: [0.02, -0.04, 0.08],
                    directions: [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],
                    reason: Some("cad.proximity".to_string()),
                },
            ],
            applied_samples: vec![
                SizingSampleApplication {
                    position_m: [0.0, 0.0, 0.0],
                    target_size_m: 0.25,
                    inserted_breakpoint_count: 2,
                    reason: Some("load_region".to_string()),
                    detail: Some("sample detail should not be copied".to_string()),
                },
                SizingSampleApplication {
                    position_m: [0.5, 0.0, 0.0],
                    target_size_m: 0.2,
                    inserted_breakpoint_count: 0,
                    reason: Some("cad.curvature".to_string()),
                    detail: Some("sample detail should not be copied".to_string()),
                },
            ],
            rejected_samples: vec![SizingSampleRejection {
                position_m: [0.1, 0.0, 0.0],
                target_size_m: 0.1,
                status: "outside_bounds".to_string(),
                reason: Some("adaptive".to_string()),
                detail: Some("rejection detail should not be copied".to_string()),
            }],
            ..MeshSizingField::default()
        },
        backend: MeshBackendSummary {
            backend: "solid".to_string(),
            cad_topology_source: "semantic_cad".to_string(),
            cad_evaluation_source: "imported_evaluator_samples".to_string(),
            cad_vertex_count: 4,
            cad_edge_count: 6,
            cad_face_count: 4,
            cad_shell_count: 1,
            cad_volume_count: 1,
            cad_imported_face_count: 3,
            cad_evaluation_evaluator_face_count: 2,
            cad_evaluation_live_query_face_count: 0,
            cad_evaluation_exact_query_face_count: 1,
            cad_evaluation_missing_exact_query_face_count: 1,
            cad_evaluation_missing_derivative_query_face_count: 2,
            cad_evaluation_missing_curvature_query_face_count: 1,
            cad_evaluation_point_supported_face_count: 2,
            cad_evaluation_projection_supported_face_count: 2,
            cad_evaluation_normal_supported_face_count: 2,
            cad_evaluation_derivative_supported_face_count: 2,
            cad_evaluation_curvature_supported_face_count: 1,
            cad_evaluation_sample_count: 8,
            cad_evaluation_rejected_sample_count: 9,
            cad_projection_query_count: 12,
            cad_derivative_query_count: 6,
            cad_curvature_query_count: 5,
            cad_uv_domain_face_count: 10,
            cad_uv_projection_out_of_bounds_count: 2,
            cad_max_projection_error_m: 2.0e-6,
            cad_max_normal_deviation: 1.0e-5,
            cad_max_curvature_estimate_1_per_m: 0.125,
            surface_cad_face_count: 3,
            surface_source_edge_loop_count: 2,
            surface_closed_edge_loop_count: 1,
            surface_conforming_source_edge_count: 5,
            surface_missing_source_edge_count: 1,
            surface_exact_cad_sample_node_count: 4,
            surface_rejected_exact_cad_sample_count: 5,
            surface_max_cad_projection_error_m: 3.0e-6,
            plc_input_node_count: 4,
            plc_input_facet_count: 4,
            plc_input_protected_edge_count: 6,
            plc_input_boundary_component_count: 1,
            plc_input_boundary_component_node_count: 4,
            plc_input_max_boundary_component_node_count: 4,
            plc_input_shell_nesting_classified: true,
            plc_input_outer_shell_count: 1,
            plc_input_nested_shell_count: 0,
            plc_input_max_shell_nesting_depth: 0,
            tetrahedron_element_count: 12,
            tetrahedron_recovered_component_ratio: 1.0,
            tetrahedron_unrecovered_component_count: 0,
            tetrahedron_volume_coverage_ratio: 0.99,
            tetrahedron_recovery_item_count: 9,
            tetrahedron_recovered_item_count: 7,
            tetrahedron_missing_recovery_item_count: 2,
            tetrahedron_recovered_boundary_face_count: 3,
            tetrahedron_recovered_protected_edge_boundary_face_count: 2,
            tetrahedron_volume_edge_source_edge_recovery_item_count: 1,
            tetrahedron_boundary_edge_source_edge_recovery_item_count: 1,
            tetrahedron_boundary_face_source_face_recovery_item_count: 1,
            tetrahedron_volume_face_source_face_recovery_item_count: 2,
            tetrahedron_deferred_absent_source_edge_recovery_item_count: 0,
            tetrahedron_attempted_absent_source_edge_recovery_item_count: 1,
            tetrahedron_reconnected_absent_source_edge_recovery_item_count: 1,
            tetrahedron_rejected_absent_source_edge_recovery_item_count: 0,
            tetrahedron_rejected_absent_source_edge_adjacent_facet_count: 0,
            tetrahedron_rejected_absent_source_edge_adjacent_facet_topology_count: 0,
            tetrahedron_rejected_absent_source_edge_current_boundary_face_count: 0,
            tetrahedron_rejected_absent_source_edge_element_topology_count: 0,
            tetrahedron_rejected_absent_source_edge_material_region_mismatch_count: 0,
            tetrahedron_rejected_absent_source_edge_quality_gate_count: 0,
            tetrahedron_recovered_absent_source_edge_boundary_face_count: 2,
            tetrahedron_attempted_source_face_diagonal_recovery_pair_count: 2,
            tetrahedron_recovered_source_face_diagonal_pair_count: 1,
            tetrahedron_recovered_source_face_diagonal_boundary_face_count: 2,
            tetrahedron_rejected_source_face_diagonal_recovery_pair_count: 1,
            tetrahedron_rejected_source_face_diagonal_adjacent_facet_count: 0,
            tetrahedron_rejected_source_face_diagonal_adjacent_facet_topology_count: 0,
            tetrahedron_rejected_source_face_diagonal_current_boundary_face_count: 1,
            tetrahedron_rejected_source_face_diagonal_element_topology_count: 0,
            tetrahedron_rejected_source_face_diagonal_material_region_mismatch_count: 0,
            tetrahedron_rejected_source_face_diagonal_quality_gate_count: 0,
            tetrahedron_repaired_boundary_face_identity_count: 1,
            tetrahedron_removed_redundant_boundary_face_count: 1,
            tetrahedron_repaired_source_face_provenance_count: 1,
            tetrahedron_repaired_source_edge_provenance_count: 2,
            tetrahedron_repaired_material_interface_element_count: 3,
            tetrahedron_attempted_material_interface_recovery_item_count: 2,
            tetrahedron_rejected_material_interface_recovery_item_count: 1,
            tetrahedron_global_material_interface_recovery_item_count: 1,
            tetrahedron_boundary_owned_material_interface_recovery_item_count: 1,
            tetrahedron_interior_material_interface_recovery_item_count: 1,
            tetrahedron_rejected_material_interface_missing_boundary_ownership_count: 1,
            tetrahedron_rejected_material_interface_ambiguous_boundary_ownership_count: 0,
            tetrahedron_attempted_absent_material_partition_recovery_item_count: 2,
            tetrahedron_inserted_absent_material_partition_recovery_item_count: 1,
            tetrahedron_inserted_absent_material_partition_element_count: 1,
            tetrahedron_inserted_absent_material_partition_boundary_face_count: 3,
            tetrahedron_rejected_absent_material_partition_recovery_item_count: 1,
            tetrahedron_rolled_back_absent_material_partition_recovery_item_count: 1,
            tetrahedron_rolled_back_absent_material_partition_element_count: 1,
            tetrahedron_rolled_back_absent_material_partition_boundary_face_count: 2,
            tetrahedron_rejected_absent_material_partition_facet_count: 0,
            tetrahedron_rejected_absent_material_partition_facet_topology_count: 1,
            tetrahedron_rejected_absent_material_partition_element_exists_count: 0,
            tetrahedron_rejected_absent_material_partition_interior_face_topology_count: 0,
            tetrahedron_rejected_absent_material_partition_quality_gate_count: 0,
            tetrahedron_rejected_absent_material_partition_post_insertion_audit_count: 1,
            tetrahedron_source_face_recovery_item_count: 5,
            tetrahedron_recovered_source_face_recovery_item_count: 3,
            tetrahedron_missing_source_face_recovery_item_count: 2,
            tetrahedron_missing_source_face_topology_recovery_item_count: 1,
            tetrahedron_missing_source_face_provenance_recovery_item_count: 1,
            tetrahedron_missing_source_face_boundary_face_recovery_item_count: 1,
            tetrahedron_missing_source_face_volume_face_recovery_item_count: 1,
            tetrahedron_missing_source_face_absent_face_recovery_item_count: 0,
            tetrahedron_missing_source_face_recovery_ids: vec!["source_face_missing_1".to_string()],
            tetrahedron_source_edge_recovery_item_count: 4,
            tetrahedron_recovered_source_edge_recovery_item_count: 3,
            tetrahedron_missing_source_edge_recovery_item_count: 1,
            tetrahedron_missing_source_edge_topology_recovery_item_count: 1,
            tetrahedron_missing_source_edge_provenance_recovery_item_count: 0,
            tetrahedron_missing_source_edge_volume_edge_recovery_item_count: 1,
            tetrahedron_missing_source_edge_absent_edge_recovery_item_count: 0,
            tetrahedron_missing_source_edge_recovery_ids: vec!["source_edge_missing_1".to_string()],
            tetrahedron_material_interface_recovery_item_count: 1,
            tetrahedron_recovered_material_interface_recovery_item_count: 0,
            tetrahedron_missing_material_interface_recovery_item_count: 1,
            tetrahedron_missing_material_interface_boundary_owned_recovery_item_count: 1,
            tetrahedron_missing_material_interface_interior_face_recovery_item_count: 2,
            tetrahedron_missing_material_interface_absent_partition_recovery_item_count: 3,
            tetrahedron_missing_material_interface_recovery_ids: vec![
                "material_interface_missing_1".to_string(),
            ],
            tetrahedron_refinement_pass_count: 2,
            tetrahedron_refinement_point_count: 5,
            tetrahedron_requested_refinement_point_count: 5,
            tetrahedron_accepted_requested_refinement_location_count: 5,
            tetrahedron_accepted_requested_refinement_point_count: 3,
            tetrahedron_accepted_requested_refinement_surrogate_point_count: 2,
            tetrahedron_rejected_requested_refinement_point_count: 1,
            tetrahedron_requested_refinement_rejected_by_reason: BTreeMap::from([(
                "quality_or_recovery".to_string(),
                1,
            )]),
            tetrahedron_dropped_requested_refinement_point_count: 2,
            tetrahedron_requested_refinement_dropped_by_reason: BTreeMap::from([(
                "not_retained_after_repair".to_string(),
                2,
            )]),
            tetrahedron_optimization_pass_count: 1,
            tetrahedron_smoothed_point_count: 2,
            tetrahedron_sliver_count: 1,
            tetrahedron_sliver_removed_count: 2,
            tetrahedron_optimization_target_seed_count: 7,
            tetrahedron_optimization_skipped_target_seed_count: 4,
            tetrahedron_optimization_rejected_edit_count: 3,
            tetrahedron_optimization_initial_max_aspect_ratio: 6.0,
            tetrahedron_optimization_final_max_aspect_ratio: 4.0,
            tetrahedron_optimization_initial_min_exact_scaled_jacobian: 0.32,
            tetrahedron_optimization_final_min_exact_scaled_jacobian: 0.40,
            tetrahedron_untangling_pass_count: 2,
            tetrahedron_untangling_initial_near_singular_count: 6,
            tetrahedron_untangling_final_near_singular_count: 1,
            tetrahedron_untangling_relocated_seed_count: 3,
            tetrahedron_untangling_reconnected_edge_star_count: 4,
            tetrahedron_untangling_reconnected_boundary_adjacent_cavity_count: 5,
            tetrahedron_untangling_reconnected_node_adjacent_cavity_count: 11,
            tetrahedron_exact_quality_repair_pass_count: 1,
            tetrahedron_exact_quality_reconnected_cavity_count: 2,
            tetrahedron_exact_quality_reconnection_quality_gain_count: 1,
            tetrahedron_exact_quality_face_neighbor_reconnected_cavity_count: 6,
            tetrahedron_exact_quality_connected_reconnected_cavity_count: 7,
            tetrahedron_exact_quality_node_adjacent_reconnected_cavity_count: 12,
            tetrahedron_exact_quality_boundary_adjacent_reconnected_cavity_count: 8,
            tetrahedron_exact_quality_expanded_connected_reconnected_cavity_count: 9,
            tetrahedron_exact_quality_split_cavity_count: 3,
            tetrahedron_exact_quality_seed_star_collapse_count: 4,
            tetrahedron_exact_quality_seed_star_relocation_count: 5,
            tetrahedron_exact_quality_unrepaired_total_count: 9,
            tetrahedron_exact_quality_unrepaired_general_cavity_count: 1,
            tetrahedron_exact_quality_unrepaired_boundary_adjacent_count: 6,
            tetrahedron_exact_quality_unrepaired_node_adjacent_count: 10,
            tetrahedron_exact_quality_unrepaired_interior_seed_count: 7,
            tetrahedron_exact_quality_unrepaired_edge_star_count: 8,
            ..MeshBackendSummary::default()
        },
        adaptive_iterations: Vec::new(),
        provenance: AnalysisMeshProvenance {
            algorithm: "test".to_string(),
            source_geometry_id: "geo".to_string(),
            source_geometry_revision: 1,
            source_geometry_sha256: None,
        },
    };

    let validation = AnalysisMeshValidationOptions {
        max_volume_element_count: Some(7),
        max_volume_component_count: Some(1),
        coverage_sample_points_m: vec![[0.1, 0.1, 0.1]],
        min_coverage_sample_ratio: 1.0,
        require_no_unrecovered_tetrahedron_components: true,
        ..AnalysisMeshValidationOptions::default()
    };
    let evidence = build_mesh_evidence_artifact(&mesh, &validation);

    assert_schema_and_rolled_back_partition_readiness_failure(&evidence);
    assert_cad_evidence(&evidence.cad);
    assert_topology_and_adaptive_evidence(&evidence);
    assert_validation_evidence(&evidence.validation);
    assert_sizing_evidence(&evidence.sizing);
    assert_tetrahedron_recovery_evidence(&evidence.tetrahedron_recovery);
    assert_region_and_quality_evidence(&evidence);
    assert_serialized_evidence(&evidence);
    assert_failed_validation_is_reported(&mesh);
    assert_validation_refresh(&mesh, &evidence);
}
