// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod business_calendar;
mod business_day_builtins;
mod calendar_duration;
mod calendar_duration_builtins;
mod capabilities;
mod char_conversion;
mod component_builtins;
mod construction;
mod constructor_builtin;
mod conversion;
mod dateshift_builtin;
mod dateshift_model;
mod descriptors;
mod indexing;
mod legacy_builtins;
mod metadata;
mod model;
mod operators;
mod prelude;
mod text_parsing;
#[cfg(test)]
mod tests;

use business_calendar::*;
#[cfg(target_arch = "wasm32")]
pub(crate) use business_day_builtins::{
    __runmat_wasm_register_builtin_busdays_builtin,
    __runmat_wasm_register_builtin_days252bus_builtin,
    __runmat_wasm_register_builtin_daysdif_builtin,
    __runmat_wasm_register_builtin_fbusdate_builtin,
    __runmat_wasm_register_builtin_holidays_builtin,
    __runmat_wasm_register_builtin_isbusday_builtin,
    __runmat_wasm_register_builtin_lbusdate_builtin,
};
use calendar_duration::*;
pub(crate) use calendar_duration::{
    calendar_duration_object_from_tensors, calendar_duration_tensors_from_value,
    datetime_format_from_value, datetime_row_times_from_calendar_step, serials_from_datetime_value,
};
pub use calendar_duration::{
    datetime_display_text, datetime_string_array, is_calendar_duration_object, is_datetime_object,
};
#[cfg(target_arch = "wasm32")]
pub(crate) use calendar_duration_builtins::{
    __runmat_wasm_register_builtin_caldays_builtin,
    __runmat_wasm_register_builtin_calendar_duration_builtin,
    __runmat_wasm_register_builtin_calmonths_builtin,
    __runmat_wasm_register_builtin_calquarters_builtin,
    __runmat_wasm_register_builtin_calweeks_builtin,
    __runmat_wasm_register_builtin_calyears_builtin,
    __runmat_wasm_register_builtin_iscalendarduration_builtin,
};
pub use capabilities::{
    DATESHIFT_EXTENSIONS, DATETIME_EXTENSIONS, DATETIME_INTEGER_CAPABILITIES, DAY_EXTENSIONS,
    HOUR_EXTENSIONS, MINUTE_EXTENSIONS, MONTH_EXTENSIONS, YEAR_EXTENSIONS,
};
pub use char_conversion::datetime_char_array;
#[cfg(target_arch = "wasm32")]
pub(crate) use component_builtins::{
    __runmat_wasm_register_builtin_clock_builtin, __runmat_wasm_register_builtin_day_builtin,
    __runmat_wasm_register_builtin_hour_builtin, __runmat_wasm_register_builtin_isdatetime_builtin,
    __runmat_wasm_register_builtin_minute_builtin, __runmat_wasm_register_builtin_month_builtin,
    __runmat_wasm_register_builtin_now_builtin, __runmat_wasm_register_builtin_second_builtin,
    __runmat_wasm_register_builtin_today_builtin, __runmat_wasm_register_builtin_year_builtin,
};
use construction::*;
#[cfg(target_arch = "wasm32")]
pub(crate) use constructor_builtin::__runmat_wasm_register_builtin_datetime_builtin;
pub use conversion::datetime_summary;
use conversion::*;
#[cfg(target_arch = "wasm32")]
pub(crate) use dateshift_builtin::__runmat_wasm_register_builtin_dateshift_builtin;
use dateshift_model::*;
pub use descriptors::{
    DATESHIFT_DESCRIPTOR, DATESHIFT_INTEGER_CAPABILITIES, DATETIME_BINARY_DESCRIPTOR,
    DATETIME_DAY_DESCRIPTOR, DATETIME_DESCRIPTOR, DATETIME_HOUR_DESCRIPTOR,
    DATETIME_MINUTE_DESCRIPTOR, DATETIME_MONTH_DESCRIPTOR, DATETIME_SECOND_DESCRIPTOR,
    DATETIME_SUBSASGN_DESCRIPTOR, DATETIME_SUBSREF_DESCRIPTOR, DATETIME_YEAR_DESCRIPTOR,
    DAY_INTEGER_CAPABILITIES, HOUR_INTEGER_CAPABILITIES, MINUTE_INTEGER_CAPABILITIES,
    MONTH_INTEGER_CAPABILITIES, SECOND_INTEGER_AUDIT, YEAR_INTEGER_CAPABILITIES,
};
use indexing::*;
#[cfg(target_arch = "wasm32")]
pub(crate) use legacy_builtins::{
    __runmat_wasm_register_builtin_datenum_builtin, __runmat_wasm_register_builtin_datestr_builtin,
    __runmat_wasm_register_builtin_datevec_builtin, __runmat_wasm_register_builtin_eomday_builtin,
    __runmat_wasm_register_builtin_etime_builtin, __runmat_wasm_register_builtin_isbetween_builtin,
    __runmat_wasm_register_builtin_weekday_builtin,
};
use metadata::*;
use model::*;
pub(crate) use model::{
    datenum_from_naive, datetime_object_from_serial_tensor, naive_from_datenum,
    serial_tensor_for_object,
};
#[cfg(target_arch = "wasm32")]
pub(crate) use operators::{
    __runmat_wasm_register_builtin_calendar_duration_eq,
    __runmat_wasm_register_builtin_calendar_duration_minus,
    __runmat_wasm_register_builtin_calendar_duration_ne,
    __runmat_wasm_register_builtin_calendar_duration_plus,
    __runmat_wasm_register_builtin_datetick_builtin, __runmat_wasm_register_builtin_datetime_eq,
    __runmat_wasm_register_builtin_datetime_ge, __runmat_wasm_register_builtin_datetime_gt,
    __runmat_wasm_register_builtin_datetime_le, __runmat_wasm_register_builtin_datetime_lt,
    __runmat_wasm_register_builtin_datetime_minus, __runmat_wasm_register_builtin_datetime_ne,
    __runmat_wasm_register_builtin_datetime_plus, __runmat_wasm_register_builtin_datetime_subsasgn,
    __runmat_wasm_register_builtin_datetime_subsref,
};
use prelude::*;
use text_parsing::*;
