use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "single-field", title: "Remove one field", program: "s = struct('name', 'entry', 'score', 42);\nt = rmfield(s, 'score')", display_output: Some("t contains only the name field"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isfield(s, 'score'));\nassert(~isfield(t, 'score'));\nassert(strcmp(t.name, 'entry'));" } },
    BuiltinExample { id: "name-cell", title: "Remove fields listed in a cell array", program: "cfg = struct('mode', 'fast', 'rate', 60, 'debug', true);\ntrimmed = rmfield(cfg, {'rate', 'debug'})", display_output: Some("trimmed contains only the mode field"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fieldnames(trimmed), {'mode'}));\nassert(strcmp(trimmed.mode, 'fast'));" } },
    BuiltinExample { id: "string-array", title: "Remove fields listed in a string array", program: "stats = struct('mean', 10, 'median', 9, 'stdev', 2);\nreduced = rmfield(stats, [\"mean\", \"median\"])", display_output: Some("reduced contains only the stdev field"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fieldnames(reduced), {'stdev'}));\nassert(reduced.stdev == 2);" } },
    BuiltinExample { id: "structure-array", title: "Remove a field from every structure", program: "entries = struct('name', {'first', 'second'}, 'id', {101, 102});\ntrimmed = rmfield(entries, 'id')", display_output: Some("every element retains only name"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(size(trimmed), [1 2]));\nassert(isequal(fieldnames(trimmed), {'name'}));" } },
    BuiltinExample { id: "conditional", title: "Remove an optional field", program: "record = struct('id', 7, 'notes', 'draft');\nif isfield(record, 'notes')\n    record = rmfield(record, 'notes');\nend", display_output: Some("record contains only id"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(record.id == 7);\nassert(~isfield(record, 'notes'));" } },
    BuiltinExample { id: "variadic-extension", title: "Use separate field arguments in RunMat mode", program: "s = struct('a', 1, 'b', 2, 'c', 3);\nt = rmfield(s, 'a', \"b\")", display_output: Some("t contains only c"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(fieldnames(t), {'c'}));\nassert(t.c == 3);" } },
];
