// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub mod accumulation;
pub mod binning;
pub mod combinatorics;
pub mod creation;
pub mod grouping;
pub mod indexing;
pub mod introspection;
pub mod shape;
pub mod sorting_sets;
pub(crate) mod type_resolvers;
