[package]
name = "rustmat-parser"
version = "0.0.1"
edition = "2021"

[dependencies]
rustmat-lexer = { workspace = true }
logos = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rustmat-lexer = { workspace = true }
