[package]
name = "rustmat-parser"
version = "0.0.1"
edition = "2021"

[dependencies]
rustmat-lexer = { workspace = true }
logos = { workspace = true }

[dev-dependencies]
rustmat-lexer = { workspace = true }
