// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub(in crate::catalog) mod acceleration;
mod aggregate;
mod aggregation;
mod array;
pub(in crate::catalog) mod cells;
mod constants;
mod introspection;
pub(in crate::catalog) mod io;
mod logical;
pub(in crate::catalog) mod math;
mod parallel;
mod stats;
pub(in crate::catalog) mod structs;

pub use acceleration::*;
pub use aggregate::*;
use aggregation::extend_groups;
pub use array::*;
pub use cells::*;
pub use introspection::*;
pub use io::*;
pub use logical::*;
pub use math::*;
pub use parallel::*;
pub use stats::*;
pub use structs::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    acceleration::extend_entries(values);
    aggregate::extend_entries(values);
    array::extend_entries(values);
    cells::extend_entries(values);
    introspection::extend_entries(values);
    io::extend_entries(values);
    logical::extend_entries(values);
    math::extend_entries(values);
    parallel::extend_entries(values);
    stats::extend_entries(values);
    structs::extend_entries(values);
}

pub(super) fn extend_constants(values: &mut Vec<crate::BuiltinConstantCatalogEntry>) {
    array::extend_constants(values);
    constants::extend_constants(values);
}
