pub(super) fn build(path_list: &str) -> String {
    let mut contents = String::from(
        "function p = pathdef\n%PATHDEF Search path defaults generated by RunMat savepath.\n%   This file reproduces the search path at the time savepath was called.\n",
    );
    let entries: Vec<String> = super::super::path_list::split(path_list).collect();
    if !entries.is_empty() {
        contents.push_str("%\n%   Directories on the saved path (in order):\n");
        for entry in entries {
            contents.push_str("%   ");
            contents.push_str(&entry);
            contents.push('\n');
        }
    }
    contents.push('\n');
    contents.push_str("p = '");
    contents.push_str(&path_list.replace('\'', "''"));
    contents.push_str("';\nend\n");
    contents
}
