use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "single-name", title: "Test one field name", program: "s = struct('name', 'Ada', 'score', 42);\nhasScore = isfield(s, 'score')", display_output: Some("hasScore = true"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(hasScore);" } },
    BuiltinExample { id: "name-cell", title: "Test a shaped cell of names", program: "s = struct('name', 'Ada', 'score', 42);\nnames = {'name', 'department'; 'score', 'email'};\nmask = isfield(s, names)", display_output: Some("mask = logical [1 0; 1 0]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(islogical(mask));\nassert(isequal(mask, logical([1 0; 1 0])));" } },
    BuiltinExample { id: "represented-array", title: "Query a represented structure array", program: "people = struct('name', {'Ada', 'Grace'}, 'id', {101, 102});\nmask = isfield(people, [\"id\", \"department\"])", display_output: Some("mask = logical [1 0]"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(mask, logical([1 0])));" } },
    BuiltinExample { id: "optional-field", title: "Initialize an optional field", program: "cfg = struct('mode', 'fast');\nif ~isfield(cfg, 'rate')\n    cfg.rate = 60;\nend", display_output: Some("cfg.rate = 60"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(cfg.rate == 60);" } },
    BuiltinExample { id: "mixed-text-cell", title: "Mix string and character names", program: "opts = struct('Solver', 'cg', 'MaxIter', 200);\nqueries = {\"Solver\", 'Tolerances'; 'MaxIter', \"History\"};\npresent = isfield(opts, queries)", display_output: Some("present = logical [1 0; 1 0]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(present, logical([1 0; 1 0])));" } },
    BuiltinExample { id: "non-structure", title: "Query a non-structure value", program: "value = 42;\ntf = isfield(value, 'anything')", display_output: Some("tf = false"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(~tf);" } },
];
