[package]
name = "rustmat-hir"
version = "1.0.0"
edition = "2021"

[dependencies]
rustmat-parser = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rustmat-lexer = { workspace = true }
