use serde::Serialize;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub enum ParallelInferenceRule {
    Barrier,
    Broadcast,
    Cat,
    Codistributed,
    CodistributedBuild,
    Codistributor,
    Codistributor1d,
    Codistributor2dbc,
    CodistributorIsComplete,
    Distributed,
    FetchNext,
    FetchOutputs,
    FunctionalReduce,
    Gcp,
    GetCodistributor,
    GetCurrentJob,
    GetCurrentTask,
    GetCurrentWorker,
    GlobalIndices,
    Gplus,
    Iscodistributed,
    LocalPart,
    Parfeval,
    ParfevalOnAll,
    Parpool,
    Probe,
    Receive,
    Redistribute,
    Send,
    SendReceive,
    SpmdIndex,
    SpmdSize,
}
