use crate::*;

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample {
        id: "single",
        title: "Create a directory",
        program: "folder = tempname();\nstatus = mkdir(folder);\nexistsAfter = exist(folder, 'dir');\nrmdir(folder);",
        display_output: Some("status is logical true and existsAfter is nonzero"),
        compatibility: BuiltinExampleCompatibility::Matlab,
        harness: BuiltinExampleHarness::NativeFilesystem,
        fixture: BuiltinExampleFixture::None,
        requirements: BuiltinExampleRequirements::NONE,
        verification: BuiltinExampleVerification::Assertions {
            source: "assert(islogical(status) && status); assert(existsAfter ~= 0);",
        },
    },
    BuiltinExample {
        id: "missing-parent",
        title: "Create a missing parent and nested child",
        program: "parent = tempname();\nstatus = mkdir(parent, fullfile('archive', '2026'));\ncreated = exist(fullfile(parent, 'archive', '2026'), 'dir');\nrmdir(parent, 's');",
        display_output: Some("status is logical true and the nested directory exists"),
        compatibility: BuiltinExampleCompatibility::Matlab,
        harness: BuiltinExampleHarness::NativeFilesystem,
        fixture: BuiltinExampleFixture::None,
        requirements: BuiltinExampleRequirements::NONE,
        verification: BuiltinExampleVerification::Assertions {
            source: "assert(islogical(status) && status); assert(created ~= 0);",
        },
    },
    BuiltinExample {
        id: "existing",
        title: "Inspect an existing-directory result",
        program: "folder = tempname();\nmkdir(folder);\n[status, msg, msgID] = mkdir(folder);\nrmdir(folder);",
        display_output: Some("status is true and msg and msgID describe the existing directory"),
        compatibility: BuiltinExampleCompatibility::Matlab,
        harness: BuiltinExampleHarness::NativeFilesystem,
        fixture: BuiltinExampleFixture::None,
        requirements: BuiltinExampleRequirements::NONE,
        verification: BuiltinExampleVerification::Assertions {
            source: "assert(islogical(status) && status); assert(~isempty(msg)); assert(~isempty(msgID));",
        },
    },
    BuiltinExample {
        id: "single-path-hierarchy",
        title: "Create intermediate directories from one path",
        program: "root = tempname();\nfolder = fullfile(root, 'data', 'archive');\nstatus = mkdir(folder);\ncreated = exist(folder, 'dir');\nrmdir(root, 's');",
        display_output: Some("status is logical true and every path component is created"),
        compatibility: BuiltinExampleCompatibility::Matlab,
        harness: BuiltinExampleHarness::NativeFilesystem,
        fixture: BuiltinExampleFixture::None,
        requirements: BuiltinExampleRequirements::NONE,
        verification: BuiltinExampleVerification::Assertions {
            source: "assert(islogical(status) && status); assert(created ~= 0);",
        },
    },
    BuiltinExample {
        id: "character-row",
        title: "Create a directory from a character row",
        program: "folder = char(tempname());\nstatus = mkdir(folder);\ncreated = exist(folder, 'dir');\nrmdir(folder);",
        display_output: Some("character-row paths use the same filesystem operation"),
        compatibility: BuiltinExampleCompatibility::Matlab,
        harness: BuiltinExampleHarness::NativeFilesystem,
        fixture: BuiltinExampleFixture::None,
        requirements: BuiltinExampleRequirements::NONE,
        verification: BuiltinExampleVerification::Assertions {
            source: "assert(islogical(status) && status); assert(created ~= 0);",
        },
    },
    BuiltinExample {
        id: "occupied-by-file",
        title: "Capture a target-file failure",
        program: "target = tempname();\nfid = fopen(target, 'w');\nfclose(fid);\n[status, msg, msgID] = mkdir(target);\nstillFile = exist(target, 'file');\ndelete(target);",
        display_output: Some("status is logical false, diagnostics are populated, and the file remains"),
        compatibility: BuiltinExampleCompatibility::Matlab,
        harness: BuiltinExampleHarness::NativeFilesystem,
        fixture: BuiltinExampleFixture::None,
        requirements: BuiltinExampleRequirements::NONE,
        verification: BuiltinExampleVerification::Assertions {
            source: "assert(islogical(status) && ~status); assert(~isempty(msg)); assert(~isempty(msgID)); assert(stillFile ~= 0);",
        },
    },
    BuiltinExample {
        id: "diagnostic-shape",
        title: "Inspect successful diagnostic outputs",
        program: "folder = tempname();\n[status, msg, msgID] = mkdir(folder);\nmessageSize = size(msg);\nidSize = size(msgID);\nrmdir(folder);",
        display_output: Some("successful creation returns empty character rows"),
        compatibility: BuiltinExampleCompatibility::Matlab,
        harness: BuiltinExampleHarness::NativeFilesystem,
        fixture: BuiltinExampleFixture::None,
        requirements: BuiltinExampleRequirements::NONE,
        verification: BuiltinExampleVerification::Assertions {
            source: "assert(status); assert(ischar(msg) && isequal(messageSize, [1 0])); assert(ischar(msgID) && isequal(idSize, [1 0]));",
        },
    },
];
