// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod documentation;
mod function_dispatch;

pub use function_dispatch::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(function_dispatch::ENTRIES.iter().copied());
}
