// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub mod bayesopt;
pub mod classification;
pub mod classification_linear;
pub mod classification_tree;
pub mod confusionmat;
pub mod crossvalind;
pub mod cvpartition;
pub mod distance;
pub mod kmeans;
pub mod lasso;
pub mod lassoglm;
pub mod linear_model;
pub mod linkage;
pub mod lscov;
pub mod mnrfit;
pub mod optimizable_variable;
pub mod perfcurve;
pub mod predict;
pub mod regress;
pub mod ridge;
pub mod tsne;
