[package]
name = "rustmat-snapshot"
version = "0.0.1"
edition = "2021"
authors = ["RustMat Team"]
description = "High-performance snapshot creator for preloading RustMat standard library"
license = "MIT OR Apache-2.0"
keywords = ["matlab", "octave", "snapshot", "serialization", "performance"]
categories = ["science", "development-tools", "compilers"]

[features]
default = ["compression", "validation"]
compression = ["lz4", "zstd"]
validation = ["sha2", "blake3", "crc32fast"]
blas-lapack = ["rustmat-runtime/blas-lapack"]

[dependencies]
rustmat-builtins = { path = "../rustmat-builtins" }
rustmat-runtime = { path = "../rustmat-runtime" }
rustmat-hir = { path = "../rustmat-hir" }
rustmat-ignition = { path = "../rustmat-ignition" }
rustmat-parser = { path = "../rustmat-parser" }
rustmat-gc = { path = "../rustmat-gc" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"
log = "0.4"
thiserror = "1.0"

# Compression support
lz4 = { version = "1.24", optional = true }
zstd = { version = "0.13", optional = true }

# Validation support  
sha2 = { version = "0.10", optional = true }

# Memory mapping for efficient loading
memmap2 = "0.9"

# Atomic operations for thread safety
parking_lot = "0.12"

# Progress reporting
indicatif = "0.17"

# CLI framework
clap = { version = "4.4", features = ["derive"] }

# Logging and time utilities
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.10"

# Additional hash algorithms
blake3 = { version = "1.5", optional = true }
crc32fast = { version = "1.3", optional = true }

# System information
libc = "0.2"

# Async runtime
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.8"
env_logger = "0.10"



[[bin]]
name = "rustmat-snapshot-tool"
path = "src/bin/tool.rs"

[lib]
name = "rustmat_snapshot"