// Auto-generated by runmatfunc
pub(crate) mod acos;
pub(crate) mod acosh;
pub(crate) mod asin;
pub(crate) mod asinh;
pub(crate) mod atan;
pub(crate) mod atan2;
pub(crate) mod atanh;
pub(crate) mod cos;
pub(crate) mod cosh;
pub(crate) mod sin;
pub(crate) mod sinh;
pub(crate) mod tan;
pub(crate) mod tanh;
