use crate::*;

pub(super) const DOCUMENTATION: BuiltinDocumentation = BuiltinDocumentation {
    authority: BuiltinDocumentationAuthority::Catalog, title: Some("dir"), slug: Some("dir"), summary: "List files and folders with metadata.",
    description: "`dir` lists local files and folders and returns their names, containing folders, modification times, sizes, and directory flags.",
    keywords: &["dir", "files", "folders", "metadata", "wildcard", "listing"], related: &["ls", "what", "isfile", "isfolder", "fullfile"],
    sections: &[
        BuiltinDocumentationSection { heading: "Paths and patterns", paragraphs: &["With no input, `dir` lists the current folder. A file path returns one metadata record; a folder path lists that folder; and `*`, `?`, and supported `**` components select matching entries. Relative paths use the current folder and a leading `~` uses the active environment.", "`dir(folder, pattern)` keeps the base folder and wildcard separate. This two-input convenience form is available in RunMat mode; use `dir(fullfile(folder, pattern))` for source that must remain within the MATLAB-compatible subset."] },
        BuiltinDocumentationSection { heading: "Returned metadata", paragraphs: &["The column result has `name`, `folder`, `date`, `bytes`, `isdir`, and `datenum` fields. `folder` is the absolute containing folder, `bytes` is a double byte count, `isdir` is logical, and the date fields describe the last observed modification time.", "A folder listing includes `.` and `..`. A missing well-formed path or wildcard with no matches returns an empty result. Results use platform-aware name ordering."] },
        BuiltinDocumentationSection { heading: "Execution boundary", paragraphs: &["Directory enumeration and metadata lookup use RunMat's filesystem service on native and browser/WASM targets. Remote HTTP, HTTPS, authenticated, FTP, and SFTP locations are not currently resolved by this builtin.", "Paths must be host text. Numeric and provider-resident inputs reject before provider or filesystem access; `dir` is not an accelerator or fusion operation."] },
    ],
    examples: super::examples::EXAMPLES, example_exemption: None, faqs: super::faqs::FAQS,
    links: &[BuiltinDocumentationLink { label: "ls", target: BuiltinDocumentationLinkTarget::Builtin("ls") }, BuiltinDocumentationLink { label: "what", target: BuiltinDocumentationLinkTarget::Builtin("what") }, BuiltinDocumentationLink { label: "isfile", target: BuiltinDocumentationLinkTarget::Builtin("isfile") }, BuiltinDocumentationLink { label: "isfolder", target: BuiltinDocumentationLinkTarget::Builtin("isfolder") }], media: &[],
    evidence: BuiltinDocumentationEvidence { implementation: &[BuiltinDocumentationLink { label: "Directory listing runtime", target: BuiltinDocumentationLinkTarget::Source("https://github.com/runmat-org/runmat/blob/main/crates/runmat-runtime/src/builtins/io/repl_fs/directory_listing/dir") }], verification: &[BuiltinEvidenceReference { kind: BuiltinEvidenceKind::UnitTest, label: "Directory metadata and pattern behavior", location: "builtins::io::repl_fs::directory_listing::dir::tests" }, BuiltinEvidenceReference { kind: BuiltinEvidenceKind::IntegrationTest, label: "Executable filesystem examples", location: "scripts/runtime/verify-builtin-examples.mjs" }], notes: &[] },
    introduced: Some("before R2006a"), status: Some(BuiltinDocumentationStatus::Stable),
};
