use crate::*;

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "current-folder", title: "List the current folder", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'current.txt'), 'w'); fclose(fid);\nstart = cd(root);\nlisting = dir;\ncd(start);\nfound = false;\nfor k = 1:numel(listing)\n    found = found || strcmp(listing(k).name, 'current.txt');\nend\nrmdir(root, 's');", display_output: Some("listing includes current.txt"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(found);" } },
    BuiltinExample { id: "folder", title: "List a folder", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'alpha.txt'), 'w'); fclose(fid);\nmkdir(fullfile(root, 'nested'));\nlisting = dir(root);\nfound_alpha = false;\nfound_nested = false;\nfor k = 1:numel(listing)\n    found_alpha = found_alpha || strcmp(listing(k).name, 'alpha.txt');\n    found_nested = found_nested || strcmp(listing(k).name, 'nested');\nend\nrmdir(root, 's');", display_output: Some("listing includes alpha.txt and nested"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(found_alpha);\nassert(found_nested);" } },
    BuiltinExample { id: "single-file", title: "Inspect one file", program: "root = tempname();\nmkdir(root);\nfile = fullfile(root, 'payload.bin');\nfid = fopen(file, 'w'); fwrite(fid, uint8([1 2 3])); fclose(fid);\ninfo = dir(file);\nrmdir(root, 's');", display_output: Some("info describes payload.bin"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(strcmp(info.name, 'payload.bin'));\nassert(~info.isdir);\nassert(info.bytes == 3);" } },
    BuiltinExample { id: "wildcard", title: "Match a wildcard", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'first.m'), 'w'); fclose(fid);\nfid = fopen(fullfile(root, 'notes.txt'), 'w'); fclose(fid);\nlisting = dir(fullfile(root, '*.m'));\nrmdir(root, 's');", display_output: Some("listing contains first.m"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(numel(listing) == 1);\nassert(strcmp(listing.name, 'first.m'));" } },
    BuiltinExample { id: "folder-pattern", title: "Match within a folder", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'one.csv'), 'w'); fclose(fid);\nfid = fopen(fullfile(root, 'two.txt'), 'w'); fclose(fid);\nlisting = dir(root, '*.csv');\nrmdir(root, 's');", display_output: Some("listing contains one.csv"), compatibility: BuiltinExampleCompatibility::RunMat, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(numel(listing) == 1);\nassert(strcmp(listing.name, 'one.csv'));" } },
    BuiltinExample { id: "missing", title: "Handle no matches", program: "root = tempname();\nmkdir(root);\nlisting = dir(fullfile(root, '*.missing'));\nrmdir(root);", display_output: Some("listing is empty"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isempty(listing));" } },
    BuiltinExample { id: "metadata", title: "Read metadata fields", program: "root = tempname();\nmkdir(root);\nfid = fopen(fullfile(root, 'sample.dat'), 'w'); fclose(fid);\ninfo = dir(fullfile(root, 'sample.dat'));\nrmdir(root, 's');", display_output: Some("info contains the standard metadata fields"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::NativeFilesystem, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isfield(info, 'name'));\nassert(isfield(info, 'folder'));\nassert(isfield(info, 'date'));\nassert(isfield(info, 'bytes'));\nassert(isfield(info, 'isdir'));\nassert(isfield(info, 'datenum'));" } },
];
