// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub(super) fn extend_aliases(_values: &mut Vec<&'static crate::BuiltinCatalogAlias>) {}
