use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "new-field", title: "Assign a new field", program: "s = struct();\ns = setfield(s, 'answer', 42)", display_output: Some("s.answer = 42"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(s.answer == 42);" } },
    BuiltinExample { id: "nested-field", title: "Create a nested field path", program: "cfg = struct();\ncfg = setfield(cfg, 'solver', 'name', 'cg');\ncfg = setfield(cfg, 'solver', 'tolerance', 1e-6)", display_output: Some("cfg.solver contains name and tolerance"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(strcmp(cfg.solver.name, 'cg'));\nassert(abs(cfg.solver.tolerance - 1e-6) < eps);" } },
    BuiltinExample { id: "structure-array-index", title: "Update one structure-array element", program: "records = struct('label', {'first', 'second'}, 'id', {101, 102});\nrecords = setfield(records, {2}, 'id', 999)", display_output: Some("records(2).id = 999"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(records(1).id == 101);\nassert(records(2).id == 999);" } },
    BuiltinExample { id: "field-subarray", title: "Assign selected field elements", program: "s = struct('values', {[10 20 30 40]});\ns = setfield(s, 'values', {[2 4]}, [200 400])", display_output: Some("s.values = [10 200 30 400]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(s.values, [10 200 30 400]));" } },
    BuiltinExample { id: "cell-parenthesis-assignment", title: "Replace one cell with parenthesis indexing", program: "s = struct('samples', {{10, 20, 30}});\ns = setfield(s, 'samples', {2}, {200})", display_output: Some("s.samples = {10, 200, 30}"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, verification: BuiltinExampleVerification::Assertions { source: "assert(s.samples{1} == 10);\nassert(s.samples{2} == 200);\nassert(s.samples{3} == 30);" } },
];
