// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

#[macro_use]
mod shared;
mod codistributors;
mod collectives;
mod context;
mod current_execution;
mod distributed_arrays;
mod documentation;
mod futures;
mod pools;

pub use codistributors::*;
pub use collectives::*;
pub use context::*;
pub use current_execution::*;
pub use distributed_arrays::*;
pub use futures::*;
pub use pools::*;
use shared::*;

pub(super) fn extend_entries(values: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    values.extend(codistributors::ENTRIES.iter().copied());
    values.extend(collectives::ENTRIES.iter().copied());
    values.extend(context::ENTRIES.iter().copied());
    values.extend(current_execution::ENTRIES.iter().copied());
    values.extend(distributed_arrays::ENTRIES.iter().copied());
    values.extend(futures::ENTRIES.iter().copied());
    values.extend(pools::ENTRIES.iter().copied());
}
