// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

mod core;

pub(super) fn extend_constants(values: &mut Vec<crate::BuiltinConstantCatalogEntry>) {
    values.extend(core::CONSTANTS.iter().copied());
}
