// Auto-generated by runmatfunc
mod all;
mod any;
mod cummax;
mod cummin;
mod cumprod;
mod cumsum;
mod diff;
mod max;
mod mean;
mod median;
mod min;
mod nnz;
mod prod;
mod std;
mod sum;
mod var;

pub use self::diff::diff_tensor_host;
pub use self::median::compute_median_inplace;
pub use cummax::evaluate as evaluate_cummax;
pub use cummin::evaluate as evaluate_cummin;
pub use max::evaluate as evaluate_max;
pub use min::evaluate as evaluate_min;
