// Auto-generated by runmatfunc
pub(crate) mod all;
pub(crate) mod any;
pub(crate) mod cummax;
pub(crate) mod cummin;
pub(crate) mod cumprod;
pub(crate) mod cumsum;
pub(crate) mod diff;
pub(crate) mod max;
pub(crate) mod mean;
pub(crate) mod median;
pub(crate) mod min;
pub(crate) mod nnz;
pub(crate) mod prod;
pub(crate) mod std;
pub(crate) mod sum;
pub(crate) mod var;

pub use self::diff::diff_tensor_host;
pub use self::median::compute_median_inplace;
pub use cummax::evaluate as evaluate_cummax;
pub use cummin::evaluate as evaluate_cummin;
pub use max::evaluate as evaluate_max;
pub use min::evaluate as evaluate_min;
