// Auto-generated by runmatfunc
pub(crate) mod all;
pub(crate) mod any;
pub(crate) mod bounds;
pub(crate) mod complex_cumulative_extrema;
pub(crate) mod cummax;
pub(crate) mod cummin;
pub(crate) mod cumprod;
pub(crate) mod cumsum;
pub(crate) mod cumtrapz;
pub(crate) mod diff;
pub(crate) mod floating_cumulative_arithmetic;
pub(crate) mod floating_cumulative_extrema;
pub(crate) mod gradient;
pub(crate) mod integer_native;
pub(crate) mod integration_common;
pub(crate) mod max;
pub(crate) mod mean;
pub(crate) mod median;
pub(crate) mod min;
pub(crate) mod moving;
pub(crate) mod nnz;
pub(crate) mod prod;
pub(crate) mod std;
pub(crate) mod sum;
pub(crate) mod topk;
pub(crate) mod trapz;
pub(crate) mod type_resolvers;
pub(crate) mod var;

pub use self::diff::diff_tensor_host;
pub use self::gradient::{
    gradient_complex_tensor_host, gradient_complex_tensor_host_with_coordinates,
    gradient_real_tensor_host, gradient_real_tensor_host_with_coordinates, matlab_gradient_shape,
};
pub use self::median::compute_median_inplace;
pub use cummax::evaluate as evaluate_cummax;
pub use cummin::evaluate as evaluate_cummin;
pub use max::evaluate as evaluate_max;
pub use min::evaluate as evaluate_min;
