pub(in crate::catalog) mod cellfun;
pub(in crate::catalog) mod core;

pub use cellfun::{
    CELLFUN_CATALOG_ENTRY, CELLFUN_DESCRIPTOR, CELLFUN_ERROR_FUNCTION_ERROR,
    CELLFUN_ERROR_INTERNAL, CELLFUN_ERROR_INVALID_INPUT, CELLFUN_ERROR_UNDEFINED_FUNCTION,
    CELLFUN_ERROR_UNIFORM_OUTPUT, CELLFUN_INTEGER_CAPABILITIES,
};
pub use core::{
    CELL2STRUCT_CATALOG_ENTRY, CELL2STRUCT_DESCRIPTOR, CELL2STRUCT_ERROR_INVALID_INPUT,
    CELL2STRUCT_ERROR_SHAPE, CELL2STRUCT_INTEGER_CAPABILITIES, CELLSTR_CATALOG_ENTRY,
    CELLSTR_CELL_INPUT_EXTENSION, CELLSTR_DESCRIPTOR, CELLSTR_ERROR_INTERNAL,
    CELLSTR_ERROR_INVALID_CONTENTS, CELLSTR_ERROR_INVALID_INPUT, CELLSTR_EXTENSIONS,
    CELLSTR_INTEGER_AUDIT, CELLSTR_SYMBOLIC_INPUT_EXTENSION, NUM2CELL_CATALOG_ENTRY,
    NUM2CELL_DESCRIPTOR, NUM2CELL_ERROR_INTERNAL, NUM2CELL_ERROR_INVALID_INPUT,
    NUM2CELL_INTEGER_CAPABILITIES,
};

pub(super) fn extend_entries(entries: &mut Vec<&'static crate::BuiltinCatalogEntry>) {
    super::extend_groups(entries, &[cellfun::ENTRIES]);
    core::extend_entries(entries);
}
