mod contract;
mod documentation_contract;

mod int16;
mod int32;
mod int64;
mod int8;
mod uint16;
mod uint32;
mod uint64;
mod uint8;

pub use int16::{
    INT16_CATALOG_ENTRY, INT16_DESCRIPTOR, INT16_ERROR_INTERNAL, INT16_ERROR_INVALID_ARGUMENT,
    INT16_ERROR_INVALID_INPUT, INT16_INTEGER_CAPABILITIES,
};
pub use int32::{
    INT32_CATALOG_ENTRY, INT32_DESCRIPTOR, INT32_ERROR_INTERNAL, INT32_ERROR_INVALID_ARGUMENT,
    INT32_ERROR_INVALID_INPUT, INT32_INTEGER_CAPABILITIES,
};
pub use int64::{
    INT64_CATALOG_ENTRY, INT64_DESCRIPTOR, INT64_ERROR_INTERNAL, INT64_ERROR_INVALID_ARGUMENT,
    INT64_ERROR_INVALID_INPUT, INT64_INTEGER_CAPABILITIES,
};
pub use int8::{
    INT8_CATALOG_ENTRY, INT8_DESCRIPTOR, INT8_ERROR_INTERNAL, INT8_ERROR_INVALID_ARGUMENT,
    INT8_ERROR_INVALID_INPUT, INT8_INTEGER_CAPABILITIES,
};
pub use uint16::{
    UINT16_CATALOG_ENTRY, UINT16_DESCRIPTOR, UINT16_ERROR_INTERNAL, UINT16_ERROR_INVALID_ARGUMENT,
    UINT16_ERROR_INVALID_INPUT, UINT16_INTEGER_CAPABILITIES,
};
pub use uint32::{
    UINT32_CATALOG_ENTRY, UINT32_DESCRIPTOR, UINT32_ERROR_INTERNAL, UINT32_ERROR_INVALID_ARGUMENT,
    UINT32_ERROR_INVALID_INPUT, UINT32_INTEGER_CAPABILITIES,
};
pub use uint64::{
    UINT64_CATALOG_ENTRY, UINT64_DESCRIPTOR, UINT64_ERROR_INTERNAL, UINT64_ERROR_INVALID_ARGUMENT,
    UINT64_ERROR_INVALID_INPUT, UINT64_INTEGER_CAPABILITIES,
};
pub use uint8::{
    UINT8_CATALOG_ENTRY, UINT8_DESCRIPTOR, UINT8_ERROR_INTERNAL, UINT8_ERROR_INVALID_ARGUMENT,
    UINT8_ERROR_INVALID_INPUT, UINT8_INTEGER_CAPABILITIES,
};

pub(super) const ENTRIES: &[&crate::BuiltinCatalogEntry] = &[
    &INT8_CATALOG_ENTRY,
    &INT16_CATALOG_ENTRY,
    &INT32_CATALOG_ENTRY,
    &INT64_CATALOG_ENTRY,
    &UINT8_CATALOG_ENTRY,
    &UINT16_CATALOG_ENTRY,
    &UINT32_CATALOG_ENTRY,
    &UINT64_CATALOG_ENTRY,
];

#[cfg(test)]
mod tests;
