// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub mod compat;
pub mod erase;
pub mod erasebetween;
pub mod extractbetween;
pub mod join;
pub mod lower;
pub mod pad;
pub mod replace;
pub mod split;
pub mod strcat;
pub mod strip;
pub mod strjoin;
pub mod strrep;
pub mod strtrim;
pub mod upper;
