import {
  childPathAttribute, parseCompositionProduct, parseModuleCompositionProjection,
} from "./schema.mjs";

const HEADER = "// @generated by RunMat builtin module composition. Do not edit.\n// Projection schema: runmat-builtin-module-composition-projection/v2";

export function generateModuleCompositionProducts(value) {
  const projection = parseModuleCompositionProjection(value);
  return projection.products.map((product) => ({
    product_id: product.product_id,
    path: product.path,
    content: renderModuleCompositionProduct(product),
  }));
}

export function renderModuleCompositionProduct(value) {
  const product = parseCompositionProduct(value);
  const sections = [HEADER, declarations(product)];
  const exports = reexports(product.children);
  if (exports) sections.push(exports);
  if (product.crate_role === "catalog") {
    for (const role of product.aggregations) {
      const children = product.children.flatMap((child) => {
        const source = child.aggregation_sources.find((entry) => entry.role === role);
        return source ? [{ child, source }] : [];
      });
      sections.push(aggregation(role, children));
    }
  }
  return `${sections.filter(Boolean).join("\n\n")}\n`;
}

export function generatedHeader() { return HEADER; }

function declarations(product) {
  return product.children.map((child) => {
    const attributes = featureLines(child);
    const sourcePath = childPathAttribute(product.path, child);
    if (sourcePath !== null) attributes.push(`#[path = "${sourcePath}"]`);
    if (child.macro_use) attributes.push("#[macro_use]");
    attributes.push(`${visibility(child.visibility)}mod ${child.module};`);
    return attributes.join("\n");
  }).join("\n");
}

function reexports(children) {
  return children.filter((child) => child.reexport.kind !== "none").map((child) => {
    const target = child.reexport.kind === "glob" ? "*" : `{${child.reexport.items.join(", ")}}`;
    return withFeature(child, `${visibility(child.reexport.visibility)}use ${child.module}::${target};`);
  }).join("\n");
}

function aggregation(role, contributions) {
  const config = {
    entries: ["&'static crate::BuiltinCatalogEntry", "extend_entries", "ENTRIES"],
    aliases: ["&'static crate::BuiltinCatalogAlias", "extend_aliases", "ALIASES"],
    constants: ["crate::BuiltinConstantCatalogEntry", "extend_constants", "CONSTANTS"],
  }[role];
  const [type, functionName, constant] = config;
  const rows = contributions.flatMap(({ child, source }) => [
    ...featureLines(child).map((line) => `    ${line}`),
    `    ${aggregationStatement(child.module, source.kind, functionName, constant)}`,
  ]);
  return [
    `pub(super) fn ${functionName}(values: &mut Vec<${type}>) {`,
    ...rows,
    "}",
  ].join("\n");
}

function aggregationStatement(module, sourceKind, functionName, constant) {
  if (sourceKind === "function") return `${module}::${functionName}(values);`;
  if (sourceKind === "groups") {
    return `values.extend(${module}::ENTRY_GROUPS.iter().flat_map(|group| group.iter().copied()));`;
  }
  return `values.extend(${module}::${constant}.iter().copied());`;
}

function withFeature(child, statement) {
  const lines = featureLines(child);
  return lines.length ? `${lines.join("\n")}\n${statement}` : statement;
}

function featureLines(child) {
  if (child.feature_policy.kind === "always") return [];
  if (child.feature_policy.kind === "test") return ["#[cfg(test)]"];
  return [`#[cfg(feature = "${child.feature_policy.feature}")]`];
}

function visibility(value) {
  return {
    private: "", super: "pub(super) ", crate: "pub(crate) ",
    catalog: "pub(in crate::catalog) ", public: "pub ",
  }[value];
}
