import { conditionAttribute } from "./condition.mjs";
import { childPathAttribute, parseCompositionProduct, parseModuleCompositionProjection } from "./schema.mjs";

const HEADER = "// @generated by RunMat builtin module composition. Do not edit.\n// Projection schema: runmat-builtin-module-composition-projection/v3";

export function generateModuleCompositionProducts(value) {
  const projection = parseModuleCompositionProjection(value);
  return projection.products.map((product) => ({ product_id: product.product_id, path: product.path, content: renderModuleCompositionProduct(product) }));
}

export function renderModuleCompositionProduct(value) {
  const product = parseCompositionProduct(value);
  const sections = [HEADER, declarations(product)];
  const exports = reexports(product.children);
  if (exports) sections.push(exports);
  if (product.crate_role === "catalog") {
    for (const role of product.aggregations) {
      const contributions = product.children.flatMap((child) => child.aggregation_sources
        .filter((source) => source.role === role).map((source) => ({ child, source })))
        .sort((left, right) => left.source.order - right.source.order);
      sections.push(aggregation(role, contributions));
    }
  }
  return `${sections.filter(Boolean).join("\n\n")}\n`;
}

export function generatedHeader() { return HEADER; }

function declarations(product) {
  return product.children.map((child) => {
    const attributes = conditionLines(child.declaration_condition);
    const sourcePath = childPathAttribute(product.path, child);
    if (sourcePath !== null) attributes.push(`#[path = "${sourcePath}"]`);
    if (child.macro_use) attributes.push("#[macro_use]");
    attributes.push(`${visibility(child.visibility)}mod ${child.module};`);
    return attributes.join("\n");
  }).join("\n");
}

function reexports(children) {
  return children.flatMap((child) => child.reexports.map((entry) => {
    const attributes = conditionLines(entry.condition);
    if (entry.doc_hidden) attributes.push("#[doc(hidden)]");
    if (entry.kind === "glob") attributes.push(`${visibility(entry.visibility)}use ${child.module}::*;`);
    else attributes.push(
      `${visibility(entry.visibility)}use ${child.module}::{`,
      ...entry.items.map((item) => `    ${item.name}${item.alias === null ? "" : ` as ${item.alias}`},`),
      "};",
    );
    return attributes.join("\n");
  })).join("\n");
}

function aggregation(role, contributions) {
  const [type, functionName, constant] = {
    entries: ["&'static crate::BuiltinCatalogEntry", "extend_entries", "ENTRIES"],
    aliases: ["&'static crate::BuiltinCatalogAlias", "extend_aliases", "ALIASES"],
    constants: ["crate::BuiltinConstantCatalogEntry", "extend_constants", "CONSTANTS"],
  }[role];
  const rows = contributions.flatMap(({ child, source }) => [
    ...conditionLines(child.declaration_condition).map((line) => `    ${line}`),
    `    ${aggregationStatement(child.module, source.kind, functionName, constant)}`,
  ]);
  return [`pub(super) fn ${functionName}(values: &mut Vec<${type}>) {`, ...rows, "}"].join("\n");
}

function aggregationStatement(module, sourceKind, functionName, constant) {
  if (sourceKind === "function") return `${module}::${functionName}(values);`;
  if (sourceKind === "groups") return `values.extend(${module}::ENTRY_GROUPS.iter().flat_map(|group| group.iter().copied()));`;
  return `values.extend(${module}::${constant}.iter().copied());`;
}

function conditionLines(condition) {
  const attribute = conditionAttribute(condition);
  return attribute === null ? [] : [attribute];
}

function visibility(value) {
  return { private: "", super: "pub(super) ", crate: "pub(crate) ", catalog: "pub(in crate::catalog) ", public: "pub " }[value];
}
