[package]
name = "rustmat-ignition"
version = "0.0.1"
edition = "2021"

[dependencies]
rustmat-builtins = { workspace = true }
rustmat-runtime = { workspace = true }
rustmat-lexer = { workspace = true }
rustmat-parser = { workspace = true }
rustmat-hir = { workspace = true }
rustmat-gc = { workspace = true }

[dev-dependencies]
rustmat-lexer = { workspace = true }
