name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1

      - name: Format
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Check
        run: cargo check --all-targets

      - name: Test
        run: cargo test --all-targets --all-features -- --format=json | tee test.json

      - name: Test Report
        if: always()
        uses: dorny/test-summary@v1
        with:
          name: test results
          path: test.json
          reporter: rust
