// @generated by RunMat builtin module composition. Do not edit.
// Projection schema: runmat-builtin-module-composition-projection/v5

pub mod dependencies;
pub mod details;
pub mod documents;
pub mod embeddings;
pub mod encode;
pub mod encoding;
pub mod entities;
pub mod file_text;
pub mod html;
pub mod lemmas;
pub mod ngrams;
pub mod normalize;
pub mod pos;
pub mod sentiment;
pub mod similarity;
pub mod stopwords;
