use crate::{
    BuiltinExample, BuiltinExampleCompatibility, BuiltinExampleHarness, BuiltinExampleVerification,
};

pub(super) const EXAMPLES: &[BuiltinExample] = &[
    BuiltinExample { id: "scalar-field", title: "Read a scalar structure field", program: "stats = struct('mean', 42, 'stdev', 3.5);\nmu = getfield(stats, 'mean')", display_output: Some("mu = 42"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(mu == 42);\nassert(class(mu) == \"double\");" } },
    BuiltinExample { id: "nested-field", title: "Traverse nested fields", program: "cfg = struct('solver', struct('name', 'cg', 'tolerance', 1e-6));\ntol = getfield(cfg, 'solver', 'tolerance')", display_output: Some("tol = 1.0000e-06"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(abs(tol - 1e-6) < eps);" } },
    BuiltinExample { id: "structure-array-index", title: "Read one structure-array element", program: "records = struct('label', {'first', 'second'}, 'id', {101, 102});\nlast_id = getfield(records, {2}, 'id')", display_output: Some("last_id = 102"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(last_id == 102);" } },
    BuiltinExample { id: "field-subarray", title: "Read selected field elements", program: "s = struct('values', {[10 20 30 40]});\nselected = getfield(s, 'values', {[2 4]})", display_output: Some("selected = [20 40]"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(selected, [20 40]));" } },
    BuiltinExample { id: "structure-array-default", title: "Read the first structure-array element by default", program: "records = struct('label', {'first', 'second'}, 'id', {101, 102});\nfirst_label = getfield(records, 'label')", display_output: Some("first_label = 'first'"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(strcmp(first_label, 'first'));" } },
    BuiltinExample { id: "matrix-element", title: "Read a matrix element stored in a field", program: "measurements = struct('values', {[1 2 3; 4 5 6]});\nentry = getfield(measurements, 'values', {2, 3})", display_output: Some("entry = 6"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(entry == 6);" } },
    BuiltinExample { id: "typed-index", title: "Use an integer selector without changing the field class", program: "s = struct('values', {uint16([10 20 30])});\nselected = getfield(s, 'values', {uint8([3 1])})", display_output: Some("selected = uint16([30 10])"), compatibility: BuiltinExampleCompatibility::Matlab, harness: BuiltinExampleHarness::Portable, fixture: crate::BuiltinExampleFixture::None, requirements: crate::BuiltinExampleRequirements::NONE, verification: BuiltinExampleVerification::Assertions { source: "assert(isequal(selected, uint16([30 10])));\nassert(strcmp(class(selected), 'uint16'));" } },
];
